In [9]:
import os

In [10]:
os.getcwd()

'C:\\Users\\Prashanth Yerabati\\Python Lab'

In [3]:
os.chdir('C:\\Users\Prashanth Yerabati\python_work')

In [4]:
os.getcwd()

'C:\\Users\\Prashanth Yerabati\\python_work'

In [5]:
os.chdir('C:\\Users\Prashanth Yerabati')

In [6]:
os.getcwd()

'C:\\Users\\Prashanth Yerabati'

In [7]:
os.mkdir('C:\\Users\\Prashanth Yerabati\\test_1031')

In [10]:
os.listdir('C:\\Users\Prashanth Yerabati')

['.anaconda',
 '.conda',
 '.condarc',
 '.dotnet',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.VirtualBox',
 '2016-01-20-02-57-55.014-VirtualBox.exe-5992.log',
 '2016-01-28-23-11-36.050-VirtualBox.exe-10108.log',
 '3D Objects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'day1_lab1.ipynb',
 'day1_practice1.ipynb',
 'Day2 Lab',
 'Desktop',
 'Documents',
 'Downloads',
 'DS_Python',
 'Favorites',
 'iCloudDrive',
 'Links',
 'Local Settings',
 'matches2008-2016.csv',
 'matches2017.csv',
 'MicrosoftEdgeBackups',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{90c996d5-62fa-11e8-9ce2-002713f3218a}.TM.blf',
 'NTUSER.DAT{90c996d5-62fa-11e8-9ce2-002713f3218a}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{90c996d5-62fa-11e8-9ce2-002713f3218a}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'python_work',
 'python_work.ipynb',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'source',
 'Start Menu',
 'Templates',
 'test.py.ipynb',
 'test1',
 'test_1031',
 'Tracing',
 'Untitled.ipynb',
 'Videos',
 'VirtualBox VMs']

In [5]:
x = 20
print(type(x))
X = [1,2,3, 4, ['a', 'b']]
print(type(X))

<class 'int'>
<class 'list'>

In [12]:
x = 10.5
print(x)
print(type(x))

10.5
<class 'float'>

In [13]:
y = 'Hello World'
print(y)
print(type(y))

Hello World
<class 'str'>

In [15]:
list1 = [1, 2, 3, 4, 5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>

In [16]:
z = 20
print(x+z)

30.5

In [19]:
dict1 = {'Name': 'Prashanth', 'Age': 38, 'Class': 'First'}
print(dict1['Name'])
print(dict1['Age'])
print(dict1['Class'])
print(type(dict1))

Prashanth
38
First
<class 'dict'>

In [1]:
x=20
print(type(x))

<class 'int'>

In [21]:
dict2 = {'Name': 'Your Name', 'Age': 'Your Age', 'games': 'games interested'}
print(dict2['Name'])
print(dict2['Age'])
print(dict2['games'])
print(type(dict2))

Your Name
Your Age
games interested
<class 'dict'>

PANDAS INTRODUCTION

In [11]:
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [12]:
Data = [1, 2, 3, 4, 5]
df = pd.DataFrame(Data,columns=['A'])
print(df)

   A
0  1
1  2
2  3
3  4
4  5

In [30]:
Data = [['Alex', 10], ['Bob', 12], ['Clarke', 13]]
df = pd.DataFrame(Data,columns =['Name', 'Age'], dtype=float)
print(df)

     Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0

In [31]:
Data = {'Name': ['Tom', 'Prashanth', 'Satish', 'Ravi', 'Satyam'], 'Age': [12, 13, 10, 33, 26]}
df = pd.DataFrame(Data, columns=['Name', 'Age'], dtype=float,index=['rank1', 'rank2','rank3', 'rank4', 'rank5'])
print(df)

            Name   Age
rank1        Tom  12.0
rank2  Prashanth  13.0
rank3     Satish  10.0
rank4       Ravi  33.0
rank5     Satyam  26.0

In [32]:
data = [{'a': 1, 'b': 2}, {'a' : 3, 'b': 4, 'c':5}]
df = pd.DataFrame(data)
print(df)

   a  b    c
0  1  2  NaN
1  3  4  5.0

In [36]:
data = [{'age': 2.5, 'animal': 'cat', 'priority': 'yes', 'values': 1}, 
        {'age': 12.0, 'animal': 'cat', 'priority': 'yes', 'values': 10},
        {'age': 14, 'animal': 'dog', 'values': 3},
        {'age': 11, 'animal': 'dog', 'priority': 'no', 'values': 15},
        {'age': 16, 'animal': 'cat', 'priority': 'yes', 'values': 20},
        {'age': 23, 'animal': 'cat', 'values': 'no'}]
df=pd.DataFrame(data, index= ['a', 'b', 'c' , 'd', 'e', 'f'])
print(df)

    age animal priority values
a   2.5    cat      yes      1
b  12.0    cat      yes     10
c  14.0    dog      NaN      3
d  11.0    dog       no     15
e  16.0    cat      yes     20
f  23.0    cat      NaN     no

In [37]:
ipl = pd.read_csv('matches2008-2016.csv')
ipl_new = pd.read_csv('matches2017.csv')
ipl.head()

,match_id,season,city,date,team1_id,team2_id,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,player_of_match_id,venue,venue_id,umpire1,umpire2
0,2008_1,2008,Bangalore,18-04-2008,KKR,RCB,RCB,field,normal,0,KKR,140,0,Brendon McCullum,82.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,Asad Rauf,RE Koertzen
1,2008_2,2008,Chandigarh,19-04-2008,CSK,KXI,CSK,bat,normal,0,CSK,33,0,Michael Hussey,18.0,I.S. Bindra Punjab Cricket Association Stadium...,9,MR Benson,SL Shastri
2,2008_3,2008,Delhi,19-04-2008,RR,DD,RR,bat,normal,0,DD,0,9,Farveez Maharoof,60.0,"Feroz Shah Kotla Stadium, Delhi",2,Aleem Dar,GA Pratapkumar
3,2008_4,2008,Mumbai,20-04-2008,MI,RCB,MI,bat,normal,0,RCB,0,5,Mark Boucher,145.0,"Wankhede Stadium, Mumbai, Maharashtra",1,SJ Davis,DJ Harper
4,2008_5,2008,Kolkata,20-04-2008,DC,KKR,DC,bat,normal,0,KKR,0,5,David Hussey,80.0,"Eden Garden Stadium, Kolkata, West Bengal",3,BF Bowden,K Hariharan

In [39]:
print(ipl.shape)
print(ipl_new.shape)

(577, 19)
(59, 19)

In [45]:
ipl_final = ipl.copy()

In [46]:
print(ipl_final)

    match_id  season           city        date team1_id team2_id toss_winner  \
0     2008_1    2008      Bangalore  18-04-2008      KKR      RCB         RCB
1     2008_2    2008     Chandigarh  19-04-2008      CSK      KXI         CSK
2     2008_3    2008          Delhi  19-04-2008       RR       DD          RR
3     2008_4    2008         Mumbai  20-04-2008       MI      RCB          MI
4     2008_5    2008        Kolkata  20-04-2008       DC      KKR          DC
5     2008_6    2008         Jaipur  21-04-2008      KXI       RR         KXI
6     2008_7    2008      Hyderabad  22-04-2008       DC       DD          DC
7     2008_8    2008        Chennai  23-04-2008      CSK       MI          MI
8     2008_9    2008      Hyderabad  24-04-2008       DC       RR          RR
9    2008_10    2008     Chandigarh  25-04-2008      KXI       MI          MI
10   2008_11    2008      Bangalore  26-04-2008      RCB       RR          RR
11   2008_12    2008        Chennai  26-04-2008      KKR      CSK         KKR
12   2008_13    2008         Mumbai  27-04-2008       MI       DC          DC
13   2008_14    2008     Chandigarh  27-04-2008       DD      KXI          DD
14   2008_15    2008      Bangalore  28-04-2008      CSK      RCB         CSK
15   2008_16    2008        Kolkata  29-04-2008      KKR       MI         KKR
16   2008_17    2008          Delhi  30-04-2008       DD      RCB         RCB
17   2008_18    2008      Hyderabad  01-05-2008       DC      KXI         KXI
18   2008_19    2008         Jaipur  01-05-2008       RR      KKR          RR
19   2008_20    2008        Chennai  02-05-2008      CSK       DD         CSK
20   2008_21    2008      Hyderabad  25-05-2008       DC      RCB          DC
21   2008_22    2008     Chandigarh  03-05-2008      KXI      KKR         KXI
22   2008_23    2008         Mumbai  04-05-2008       MI       DD          DD
23   2008_24    2008         Jaipur  04-05-2008      CSK       RR         CSK
24   2008_25    2008      Bangalore  05-05-2008      RCB      KXI         KXI
25   2008_26    2008        Chennai  06-05-2008      CSK       DC          DC
26   2008_27    2008         Mumbai  07-05-2008       RR       MI          MI
27   2008_28    2008          Delhi  08-05-2008       DD      CSK         CSK
28   2008_29    2008        Kolkata  08-05-2008      KKR      RCB         KKR
29   2008_30    2008         Jaipur  09-05-2008       DC       RR          RR
..       ...     ...            ...         ...      ...      ...         ...
547  2016_31    2016         Rajkot  03-05-2016       GL       DD          DD
548  2016_32    2016        Kolkata  04-05-2016      KKR      KXI         KXI
549  2016_33    2016          Delhi  05-05-2016       DD      RPS         RPS
550  2016_34    2016      Hyderabad  06-05-2016       GL      SRH         SRH
551  2016_35    2016      Bangalore  07-05-2016      RPS      RCB         RCB
552  2016_36    2016     Chandigarh  07-05-2016      KXI       DD          DD
553  2016_37    2016  Visakhapatnam  08-05-2016      SRH       MI          MI
554  2016_38    2016        Kolkata  08-05-2016      KKR       GL          GL
555  2016_39    2016     Chandigarh  09-05-2016      RCB      KXI         KXI
556  2016_40    2016  Visakhapatnam  10-05-2016      SRH      RPS         SRH
557  2016_41    2016      Bangalore  11-05-2016      RCB       MI          MI
558  2016_42    2016      Hyderabad  12-05-2016      SRH       DD          DD
559  2016_43    2016  Visakhapatnam  13-05-2016       MI      KXI          MI
560  2016_44    2016      Bangalore  14-05-2016      RCB       GL          GL
561  2016_45    2016        Kolkata  14-05-2016      RPS      KKR         RPS
562  2016_46    2016     Chandigarh  15-05-2016      KXI      SRH         KXI
563  2016_47    2016  Visakhapatnam  15-05-2016       MI       DD          DD
564  2016_48    2016        Kolkata  16-05-2016      KKR      RCB         RCB
565  2016_49    2016  Visakhapatnam  17-05-2016       DD      RPS         RPS
566  2016_50    2016      Bangalore  18-05-2016      RCB      KXI         KXI
567  2016_51    2016         Kanpur  19-05-2016      KKR       GL          GL
568  2016_52    2016         Raipur  20-05-2016      SRH       DD          DD
569  2016_53    2016  Visakhapatnam  21-05-2016      KXI      RPS         KXI
570  2016_54    2016         Kanpur  21-05-2016       MI       GL          GL
571  2016_55    2016        Kolkata  22-05-2016      KKR      SRH         SRH
572  2016_56    2016         Raipur  22-05-2016       DD      RCB         RCB
573  2016_57    2016      Bangalore  24-05-2016       GL      RCB         RCB
574  2016_58    2016          Delhi  25-05-2016      SRH      KKR         KKR
575  2016_59    2016          Delhi  27-05-2016       GL      SRH         SRH
576  2016_60    2016      Bangalore  29-05-2016      SRH      RCB         SRH

    toss_decision  result  dl_applied winner  win_by_runs  win_by_wickets  \
0           field  normal           0    KKR          140               0
1             bat  normal           0    CSK           33               0
2             bat  normal           0     DD            0               9
3             bat  normal           0    RCB            0               5
4             bat  normal           0    KKR            0               5
5             bat  normal           0     RR            0               6
6             bat  normal           0     DD            0               9
7           field  normal           0    CSK            6               0
8           field  normal           0     RR            0               3
9           field  normal           0    KXI           66               0
10          field  normal           0     RR            0               7
11            bat  normal           0    CSK            0               9
12          field  normal           0     DC            0              10
13            bat  normal           0    KXI            0               4
14            bat  normal           0    CSK           13               0
15            bat  normal           0     MI            0               7
16          field  normal           0     DD           10               0
17          field  normal           0    KXI            0               7
18            bat  normal           0     RR           45               0
19            bat  normal           0     DD            0               8
20            bat  normal           0    RCB            0               5
21            bat  normal           0    KXI            9               0
22          field  normal           0     MI           29               0
23            bat  normal           0     RR            0               8
24          field  normal           0    KXI            0               6
25          field  normal           0     DC            0               7
26          field  normal           0     MI            0               7
27          field  normal           0    CSK            0               4
28            bat  normal           0    KKR            5               0
29          field  normal           0     RR            0               8
..            ...     ...         ...    ...          ...             ...
547         field  normal           0     DD            0               8
548         field  normal           0    KKR            7               0
549         field  normal           0    RPS            0               7
550         field  normal           0    SRH            0               5
551         field  normal           0    RCB            0               7
552         field  normal           0    KXI            9               0
553         field  normal           0    SRH           85               0
554         field  normal           0     GL            0               5
555         field  normal           0    RCB            1               0
556           bat  normal           0    SRH            4               0
557         field  normal           0     MI            0               6
558         field  normal           0     DD            0               7
559           bat  normal           0    KXI            0               7
560         field  normal           0    RCB          144               0
561           bat  normal           1    KKR            0               8
562           bat  normal           0    SRH            0               7
563         field  normal           0     MI           80               0
564         field  normal           0    RCB            0               9
565         field  normal           1    RPS           19               0
566         field  normal           1    RCB           82               0
567         field  normal           0     GL            0               6
568         field  normal           0     DD            0               6
569           bat  normal           0    RPS            0               4
570         field  normal           0     GL            0               6
571         field  normal           0    KKR           22               0
572         field  normal           0    RCB            0               6
573         field  normal           0    RCB            0               4
574         field  normal           0    SRH           22               0
575         field  normal           0    SRH            0               4
576           bat  normal           0    SRH            8               0

          player_of_match  player_of_match_id  \
0        Brendon McCullum                82.0
1          Michael Hussey                18.0
2        Farveez Maharoof                60.0
3            Mark Boucher               145.0
4            David Hussey                80.0
5            Shane Watson               175.0
6         Virender Sehwag                46.0
7          Matthew Hayden                 6.0
8            Yusuf Pathan               171.0
9        Kumar Sangakkara                98.0
10           Shane Watson               175.0
11             Jacob Oram                23.0
12         Adam Gilchrist                28.0
13           Simon Katich               105.0
14   Mahendra Singh Dhoni                 1.0
15      Sanath Jayasuriya               117.0
16          Glenn McGrath                50.0
17            Shaun Marsh               106.0
18       Swapnil Asnodkar               166.0
19        Virender Sehwag                46.0
20            Vinay Kumar               153.0
21           Irfan Pathan                96.0
22          Shaun Pollock               121.0
23          Sohail Tanvir               174.0
24            S Sreesanth               100.0
25         Adam Gilchrist                28.0
26           Ashish Nehra               119.0
27   Mahendra Singh Dhoni                 1.0
28         Sourav Ganguly                66.0
29           Yusuf Pathan               171.0
..                    ...                 ...
547          Rishabh Pant               572.0
548         Andre Russell               430.0
549        Ajinkya Rahane               122.0
550               B Kumar               691.0
551           Virat Kohli               149.0
552        Marcus Stoinis               540.0
553          Ashish Nehra               119.0
554         Praveen Kumar               160.0
555          Shane Watson               175.0
556            Adam Zampa               589.0
557         Krunal Pandya               582.0
558          Chris Morris               465.0
559        Marcus Stoinis               540.0
560        AB De Villiers                47.0
561          Yusuf Pathan               171.0
562           Hashim Amla               611.0
563         Krunal Pandya               582.0
564           Virat Kohli               149.0
565           Ashok Dinda                68.0
566           Virat Kohli               149.0
567          Dwayne Smith               124.0
568            Karun Nair               458.0
569  Mahendra Singh Dhoni                 1.0
570          Suresh Raina                24.0
571          Yusuf Pathan               171.0
572           Virat Kohli               149.0
573        AB De Villiers                47.0
574      Moises Henriques               212.0
575          David Warner               207.0
576           Ben Cutting               526.0

                                                 venue  venue_id  \
0           M.Chinnaswamy Stadium Bengaluru, Karnataka         7
1    I.S. Bindra Punjab Cricket Association Stadium...         9
2                      Feroz Shah Kotla Stadium, Delhi         2
3                Wankhede Stadium, Mumbai, Maharashtra         1
4            Eden Garden Stadium, Kolkata, West Bengal         3
5           Sawai Man Singh Stadium, Jaipur, Rajasthan         6
6        Rajiv Gandhi International Stadium, Hyderabad         4
7          M.A.Chidambaram Stadium Chennai, Tamil Nadu         5
8        Rajiv Gandhi International Stadium, Hyderabad         4
9    I.S. Bindra Punjab Cricket Association Stadium...         9
10          M.Chinnaswamy Stadium Bengaluru, Karnataka         7
11         M.A.Chidambaram Stadium Chennai, Tamil Nadu         5
12                          Dr DY Patil Sports Academy        10
13   I.S. Bindra Punjab Cricket Association Stadium...         9
14          M.Chinnaswamy Stadium Bengaluru, Karnataka         7
15           Eden Garden Stadium, Kolkata, West Bengal         3
16                     Feroz Shah Kotla Stadium, Delhi         2
17       Rajiv Gandhi International Stadium, Hyderabad         4
18          Sawai Man Singh Stadium, Jaipur, Rajasthan         6
19         M.A.Chidambaram Stadium Chennai, Tamil Nadu         5
20       Rajiv Gandhi International Stadium, Hyderabad         4
21   I.S. Bindra Punjab Cricket Association Stadium...         9
22                          Dr DY Patil Sports Academy        10
23          Sawai Man Singh Stadium, Jaipur, Rajasthan         6
24          M.Chinnaswamy Stadium Bengaluru, Karnataka         7
25         M.A.Chidambaram Stadium Chennai, Tamil Nadu         5
26                          Dr DY Patil Sports Academy        10
27                     Feroz Shah Kotla Stadium, Delhi         2
28           Eden Garden Stadium, Kolkata, West Bengal         3
29          Sawai Man Singh Stadium, Jaipur, Rajasthan         6
..                                                 ...       ...
547             Saurashtra Cricket Association Stadium        33
548          Eden Garden Stadium, Kolkata, West Bengal         3
549                    Feroz Shah Kotla Stadium, Delhi         2
550      Rajiv Gandhi International Stadium, Hyderabad         4
551         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
552  I.S. Bindra Punjab Cricket Association Stadium...         9
553  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        25
554          Eden Garden Stadium, Kolkata, West Bengal         3
555  I.S. Bindra Punjab Cricket Association Stadium...         9
556  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        25
557         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
558      Rajiv Gandhi International Stadium, Hyderabad         4
559  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        25
560         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
561          Eden Garden Stadium, Kolkata, West Bengal         3
562  I.S. Bindra Punjab Cricket Association Stadium...         9
563  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        25
564          Eden Garden Stadium, Kolkata, West Bengal         3
565  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        25
566         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
567                                         Green Park        34
568   Shaheed Veer Narayan Singh International Stadium        27
569  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        25
570                                         Green Park        34
571          Eden Garden Stadium, Kolkata, West Bengal         3
572   Shaheed Veer Narayan Singh International Stadium        27
573         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
574                    Feroz Shah Kotla Stadium, Delhi         2
575                    Feroz Shah Kotla Stadium, Delhi         2
576         M.Chinnaswamy Stadium Bengaluru, Karnataka         7

                   umpire1          umpire2
0                Asad Rauf      RE Koertzen
1                MR Benson       SL Shastri
2                Aleem Dar   GA Pratapkumar
3                 SJ Davis        DJ Harper
4                BF Bowden      K Hariharan
5                Aleem Dar        RB Tiffin
6                IL Howell        AM Saheba
7                DJ Harper   GA Pratapkumar
8                Asad Rauf        MR Benson
9                Aleem Dar        AM Saheba
10               MR Benson        IL Howell
11               BF Bowden   AV Jayaprakash
12               Asad Rauf       SL Shastri
13             RE Koertzen        I Shivram
14             BR Doctrove        RB Tiffin
15               BF Bowden   AV Jayaprakash
16               Aleem Dar        I Shivram
17             BR Doctrove        RB Tiffin
18             RE Koertzen   GA Pratapkumar
19               BF Bowden      K Hariharan
20               Asad Rauf      RE Koertzen
21               DJ Harper        I Shivram
22               IL Howell      RE Koertzen
23               Asad Rauf   AV Jayaprakash
24                SJ Davis      BR Doctrove
25               MR Benson        RB Tiffin
26               DJ Harper      RE Koertzen
27               Aleem Dar        RB Tiffin
28               Asad Rauf        IL Howell
29               MR Benson        AM Saheba
..                     ...              ...
547            CB Gaffaney     BNJ Oxenford
548           AK Chaudhary  HDPK Dharmasena
549          C Shamshuddin        RJ Tucker
550              M Erasmus           S Ravi
551            CB Gaffaney     BNJ Oxenford
552        HDPK Dharmasena        CK Nandan
553                 S Ravi    C Shamshuddin
554              M Erasmus        RJ Tucker
555           AK Chaudhary  HDPK Dharmasena
556            CB Gaffaney        VK Sharma
557            AY Dandekar    C Shamshuddin
558             K Bharatan        M Erasmus
559        HDPK Dharmasena        CK Nandan
560            AY Dandekar        VK Sharma
561         A Nand Kishore     BNJ Oxenford
562  KN Ananthapadmanabhan        M Erasmus
563            Nitin Menon        CK Nandan
564            CB Gaffaney   A Nand Kishore
565            Nitin Menon    C Shamshuddin
566  KN Ananthapadmanabhan        M Erasmus
567           AK Chaudhary        CK Nandan
568         A Nand Kishore     BNJ Oxenford
569        HDPK Dharmasena      Nitin Menon
570           AK Chaudhary        CK Nandan
571  KN Ananthapadmanabhan        M Erasmus
572         A Nand Kishore     BNJ Oxenford
573           AK Chaudhary  HDPK Dharmasena
574              M Erasmus    C Shamshuddin
575              M Erasmus        CK Nandan
576        HDPK Dharmasena     BNJ Oxenford

[577 rows x 19 columns]

In [47]:
ipl_final = ipl_final.append(ipl_new)

In [49]:
print(ipl_final.shape)

(636, 19)

In [50]:
print(ipl_final.head)

<bound method NDFrame.head of    match_id  season        city        date team1_id team2_id toss_winner  \
0    2008_1    2008   Bangalore  18-04-2008      KKR      RCB         RCB
1    2008_2    2008  Chandigarh  19-04-2008      CSK      KXI         CSK
2    2008_3    2008       Delhi  19-04-2008       RR       DD          RR
3    2008_4    2008      Mumbai  20-04-2008       MI      RCB          MI
4    2008_5    2008     Kolkata  20-04-2008       DC      KKR          DC
5    2008_6    2008      Jaipur  21-04-2008      KXI       RR         KXI
6    2008_7    2008   Hyderabad  22-04-2008       DC       DD          DC
7    2008_8    2008     Chennai  23-04-2008      CSK       MI          MI
8    2008_9    2008   Hyderabad  24-04-2008       DC       RR          RR
9   2008_10    2008  Chandigarh  25-04-2008      KXI       MI          MI
10  2008_11    2008   Bangalore  26-04-2008      RCB       RR          RR
11  2008_12    2008     Chennai  26-04-2008      KKR      CSK         KKR
12  2008_13    2008      Mumbai  27-04-2008       MI       DC          DC
13  2008_14    2008  Chandigarh  27-04-2008       DD      KXI          DD
14  2008_15    2008   Bangalore  28-04-2008      CSK      RCB         CSK
15  2008_16    2008     Kolkata  29-04-2008      KKR       MI         KKR
16  2008_17    2008       Delhi  30-04-2008       DD      RCB         RCB
17  2008_18    2008   Hyderabad  01-05-2008       DC      KXI         KXI
18  2008_19    2008      Jaipur  01-05-2008       RR      KKR          RR
19  2008_20    2008     Chennai  02-05-2008      CSK       DD         CSK
20  2008_21    2008   Hyderabad  25-05-2008       DC      RCB          DC
21  2008_22    2008  Chandigarh  03-05-2008      KXI      KKR         KXI
22  2008_23    2008      Mumbai  04-05-2008       MI       DD          DD
23  2008_24    2008      Jaipur  04-05-2008      CSK       RR         CSK
24  2008_25    2008   Bangalore  05-05-2008      RCB      KXI         KXI
25  2008_26    2008     Chennai  06-05-2008      CSK       DC          DC
26  2008_27    2008      Mumbai  07-05-2008       RR       MI          MI
27  2008_28    2008       Delhi  08-05-2008       DD      CSK         CSK
28  2008_29    2008     Kolkata  08-05-2008      KKR      RCB         KKR
29  2008_30    2008      Jaipur  09-05-2008       DC       RR          RR
..      ...     ...         ...         ...      ...      ...         ...
29  2017_30    2017   Bangalore  27-04-2017      RCB       GL          GL
30  2017_31    2017     Kolkata  28-04-2017       DD      KKR         KKR
31  2017_32    2017  Chandigarh  28-04-2017      SRH      KXI         KXI
32  2017_33    2017        Pune  29-04-2017      RPS      RCB         RCB
33  2017_34    2017      Rajkot  29-04-2017       GL       MI          GL
34  2017_35    2017  Chandigarh  30-04-2017       DD      KXI         KXI
35  2017_36    2017   Hyderabad  30-04-2017      SRH      KKR         KKR
36  2017_37    2017      Mumbai  01-05-2017      RCB       MI         RCB
37  2017_38    2017        Pune  01-05-2017       GL      RPS         RPS
38  2017_39    2017       Delhi  02-05-2017      SRH       DD          DD
39  2017_40    2017     Kolkata  03-05-2017      KKR      RPS         RPS
40  2017_41    2017       Delhi  04-05-2017       GL       DD          DD
41  2017_42    2017   Bangalore  05-05-2017      KXI      RCB         RCB
42  2017_43    2017   Hyderabad  06-05-2017      RPS      SRH         SRH
43  2017_44    2017       Delhi  06-05-2017       MI       DD          DD
44  2017_45    2017   Bangalore  07-05-2017      RCB      KKR         KKR
45  2017_46    2017  Chandigarh  07-05-2017      KXI       GL          GL
46  2017_47    2017   Hyderabad  08-05-2017       MI      SRH          MI
47  2017_48    2017  Chandigarh  09-05-2017      KXI      KKR         KKR
48  2017_49    2017      Kanpur  10-05-2017       GL       DD          DD
49  2017_50    2017      Mumbai  11-05-2017      KXI       MI          MI
50  2017_51    2017       Delhi  12-05-2017       DD      RPS          DD
51  2017_52    2017      Kanpur  13-05-2017       GL      SRH         SRH
52  2017_53    2017     Kolkata  13-05-2017       MI      KKR         KKR
53  2017_54    2017        Pune  14-05-2017      KXI      RPS         RPS
54  2017_55    2017       Delhi  14-05-2017      RCB       DD         RCB
55  2017_56    2017      Mumbai  16-05-2017      RPS       MI          MI
56  2017_57    2017   Bangalore  17-05-2017      SRH      KKR         KKR
57  2017_58    2017   Bangalore  19-05-2017      KKR       MI          MI
58  2017_59    2017   Hyderabad  21-05-2017       MI      RPS          MI

   toss_decision  result  dl_applied winner  win_by_runs  win_by_wickets  \
0          field  normal           0    KKR          140               0
1            bat  normal           0    CSK           33               0
2            bat  normal           0     DD            0               9
3            bat  normal           0    RCB            0               5
4            bat  normal           0    KKR            0               5
5            bat  normal           0     RR            0               6
6            bat  normal           0     DD            0               9
7          field  normal           0    CSK            6               0
8          field  normal           0     RR            0               3
9          field  normal           0    KXI           66               0
10         field  normal           0     RR            0               7
11           bat  normal           0    CSK            0               9
12         field  normal           0     DC            0              10
13           bat  normal           0    KXI            0               4
14           bat  normal           0    CSK           13               0
15           bat  normal           0     MI            0               7
16         field  normal           0     DD           10               0
17         field  normal           0    KXI            0               7
18           bat  normal           0     RR           45               0
19           bat  normal           0     DD            0               8
20           bat  normal           0    RCB            0               5
21           bat  normal           0    KXI            9               0
22         field  normal           0     MI           29               0
23           bat  normal           0     RR            0               8
24         field  normal           0    KXI            0               6
25         field  normal           0     DC            0               7
26         field  normal           0     MI            0               7
27         field  normal           0    CSK            0               4
28           bat  normal           0    KKR            5               0
29         field  normal           0     RR            0               8
..           ...     ...         ...    ...          ...             ...
29         field  normal           0     GL            0               7
30         field  normal           0    KKR            0               7
31         field  normal           0    SRH           26               0
32         field  normal           0    RPS           61               0
33           bat     tie           0     MI            0               0
34         field  normal           0    KXI            0              10
35         field  normal           0    SRH           48               0
36           bat  normal           0     MI            0               5
37         field  normal           0    RPS            0               5
38         field  normal           0     DD            0               6
39         field  normal           0    RPS            0               4
40         field  normal           0     DD            0               7
41         field  normal           0    KXI           19               0
42         field  normal           0    RPS           12               0
43         field  normal           0     MI          146               0
44         field  normal           0    KKR            0               6
45         field  normal           0     GL            0               6
46           bat  normal           0    SRH            0               7
47         field  normal           0    KXI           14               0
48         field  normal           0     DD            0               2
49         field  normal           0    KXI            7               0
50           bat  normal           0     DD            7               0
51         field  normal           0    SRH            0               8
52         field  normal           0     MI            9               0
53         field  normal           0    RPS            0               9
54           bat  normal           0    RCB           10               0
55         field  normal           0    RPS           20               0
56         field  normal           1    KKR            0               7
57         field  normal           0     MI            0               6
58           bat  normal           0     MI            1               0

         player_of_match  player_of_match_id  \
0       Brendon McCullum                82.0
1         Michael Hussey                18.0
2       Farveez Maharoof                60.0
3           Mark Boucher               145.0
4           David Hussey                80.0
5           Shane Watson               175.0
6        Virender Sehwag                46.0
7         Matthew Hayden                 6.0
8           Yusuf Pathan               171.0
9       Kumar Sangakkara                98.0
10          Shane Watson               175.0
11            Jacob Oram                23.0
12        Adam Gilchrist                28.0
13          Simon Katich               105.0
14  Mahendra Singh Dhoni                 1.0
15     Sanath Jayasuriya               117.0
16         Glenn McGrath                50.0
17           Shaun Marsh               106.0
18      Swapnil Asnodkar               166.0
19       Virender Sehwag                46.0
20           Vinay Kumar               153.0
21          Irfan Pathan                96.0
22         Shaun Pollock               121.0
23         Sohail Tanvir               174.0
24           S Sreesanth               100.0
25        Adam Gilchrist                28.0
26          Ashish Nehra               119.0
27  Mahendra Singh Dhoni                 1.0
28        Sourav Ganguly                66.0
29          Yusuf Pathan               171.0
..                   ...                 ...
29            Andrew Tye               535.0
30        Gautam Gambhir                58.0
31           Rashid Khan               634.0
32       Lockie Ferguson               627.0
33         Krunal Pandya               582.0
34        Sandeep Sharma               479.0
35          David Warner               207.0
36          Rohit Sharma                30.0
37            Ben Stokes               625.0
38        Mohammed Shami               647.0
39        Rahul Tripathi               630.0
40          Rishabh Pant               572.0
41        Sandeep Sharma               479.0
42        Jaydev Unadkat               361.0
43         Lendl Simmons               524.0
44          Sunil Narine               437.0
45          Dwayne Smith               124.0
46        Shikhar Dhawan                57.0
47          Mohit Sharma               469.0
48          Shreyas Iyer               537.0
49       Wriddhiman Saha                84.0
50            Karun Nair               458.0
51        Mohammed Siraj               681.0
52         Ambati Rayudu               309.0
53        Jaydev Unadkat               361.0
54         Harshal Patel               456.0
55     Washington Sunder               631.0
56   Nathan Coulter-Nile               484.0
57           Karn Sharma               254.0
58         Krunal Pandya               582.0

                                                venue  venue_id  \
0          M.Chinnaswamy Stadium Bengaluru, Karnataka         7
1   I.S. Bindra Punjab Cricket Association Stadium...         9
2                     Feroz Shah Kotla Stadium, Delhi         2
3               Wankhede Stadium, Mumbai, Maharashtra         1
4           Eden Garden Stadium, Kolkata, West Bengal         3
5          Sawai Man Singh Stadium, Jaipur, Rajasthan         6
6       Rajiv Gandhi International Stadium, Hyderabad         4
7         M.A.Chidambaram Stadium Chennai, Tamil Nadu         5
8       Rajiv Gandhi International Stadium, Hyderabad         4
9   I.S. Bindra Punjab Cricket Association Stadium...         9
10         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
11        M.A.Chidambaram Stadium Chennai, Tamil Nadu         5
12                         Dr DY Patil Sports Academy        10
13  I.S. Bindra Punjab Cricket Association Stadium...         9
14         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
15          Eden Garden Stadium, Kolkata, West Bengal         3
16                    Feroz Shah Kotla Stadium, Delhi         2
17      Rajiv Gandhi International Stadium, Hyderabad         4
18         Sawai Man Singh Stadium, Jaipur, Rajasthan         6
19        M.A.Chidambaram Stadium Chennai, Tamil Nadu         5
20      Rajiv Gandhi International Stadium, Hyderabad         4
21  I.S. Bindra Punjab Cricket Association Stadium...         9
22                         Dr DY Patil Sports Academy        10
23         Sawai Man Singh Stadium, Jaipur, Rajasthan         6
24         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
25        M.A.Chidambaram Stadium Chennai, Tamil Nadu         5
26                         Dr DY Patil Sports Academy        10
27                    Feroz Shah Kotla Stadium, Delhi         2
28          Eden Garden Stadium, Kolkata, West Bengal         3
29         Sawai Man Singh Stadium, Jaipur, Rajasthan         6
..                                                ...       ...
29         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
30          Eden Garden Stadium, Kolkata, West Bengal         3
31  I.S. Bindra Punjab Cricket Association Stadium...         9
32            Maharashtra Cricket Association Stadium        32
33             Saurashtra Cricket Association Stadium        33
34  I.S. Bindra Punjab Cricket Association Stadium...         9
35      Rajiv Gandhi International Stadium, Hyderabad         4
36              Wankhede Stadium, Mumbai, Maharashtra         1
37            Maharashtra Cricket Association Stadium        32
38                    Feroz Shah Kotla Stadium, Delhi         2
39          Eden Garden Stadium, Kolkata, West Bengal         3
40                    Feroz Shah Kotla Stadium, Delhi         2
41         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
42      Rajiv Gandhi International Stadium, Hyderabad         4
43                    Feroz Shah Kotla Stadium, Delhi         2
44         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
45  I.S. Bindra Punjab Cricket Association Stadium...         9
46      Rajiv Gandhi International Stadium, Hyderabad         4
47  I.S. Bindra Punjab Cricket Association Stadium...         9
48                                         Green Park        34
49              Wankhede Stadium, Mumbai, Maharashtra         1
50                    Feroz Shah Kotla Stadium, Delhi         2
51                                         Green Park        34
52          Eden Garden Stadium, Kolkata, West Bengal         3
53            Maharashtra Cricket Association Stadium        32
54                    Feroz Shah Kotla Stadium, Delhi         2
55              Wankhede Stadium, Mumbai, Maharashtra         1
56         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
57         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
58      Rajiv Gandhi International Stadium, Hyderabad         4

                  umpire1         umpire2
0               Asad Rauf     RE Koertzen
1               MR Benson      SL Shastri
2               Aleem Dar  GA Pratapkumar
3                SJ Davis       DJ Harper
4               BF Bowden     K Hariharan
5               Aleem Dar       RB Tiffin
6               IL Howell       AM Saheba
7               DJ Harper  GA Pratapkumar
8               Asad Rauf       MR Benson
9               Aleem Dar       AM Saheba
10              MR Benson       IL Howell
11              BF Bowden  AV Jayaprakash
12              Asad Rauf      SL Shastri
13            RE Koertzen       I Shivram
14            BR Doctrove       RB Tiffin
15              BF Bowden  AV Jayaprakash
16              Aleem Dar       I Shivram
17            BR Doctrove       RB Tiffin
18            RE Koertzen  GA Pratapkumar
19              BF Bowden     K Hariharan
20              Asad Rauf     RE Koertzen
21              DJ Harper       I Shivram
22              IL Howell     RE Koertzen
23              Asad Rauf  AV Jayaprakash
24               SJ Davis     BR Doctrove
25              MR Benson       RB Tiffin
26              DJ Harper     RE Koertzen
27              Aleem Dar       RB Tiffin
28              Asad Rauf       IL Howell
29              MR Benson       AM Saheba
..                    ...             ...
29           AK Chaudhary   C Shamshuddin
30               NJ Llong          S Ravi
31            Nitin Menon       CK Nandan
32  KN Ananthapadmanabhan       M Erasmus
33           AK Chaudhary     CB Gaffaney
34               YC Barde       CK Nandan
35            AY Dandekar          S Ravi
36           AK Chaudhary     CB Gaffaney
37              M Erasmus   C Shamshuddin
38               YC Barde     Nitin Menon
39  KN Ananthapadmanabhan  A Nand Kishore
40              M Erasmus     Nitin Menon
41            CB Gaffaney   C Shamshuddin
42  KN Ananthapadmanabhan    AK Chaudhary
43            Nitin Menon       CK Nandan
44            AY Dandekar   C Shamshuddin
45         A Nand Kishore       VK Sharma
46  KN Ananthapadmanabhan       M Erasmus
47         A Nand Kishore          S Ravi
48               YC Barde    AK Chaudhary
49             A Deshmukh  A Nand Kishore
50  KN Ananthapadmanabhan       CK Nandan
51           AK Chaudhary     Nitin Menon
52         A Nand Kishore          S Ravi
53            AY Dandekar      A Deshmukh
54              CK Nandan   C Shamshuddin
55                 S Ravi   C Shamshuddin
56           AK Chaudhary     Nitin Menon
57               NJ Llong     Nitin Menon
58               NJ Llong          S Ravi

[636 rows x 19 columns]>

In [51]:
print(ipl_final.tail)

<bound method NDFrame.tail of    match_id  season        city        date team1_id team2_id toss_winner  \
0    2008_1    2008   Bangalore  18-04-2008      KKR      RCB         RCB
1    2008_2    2008  Chandigarh  19-04-2008      CSK      KXI         CSK
2    2008_3    2008       Delhi  19-04-2008       RR       DD          RR
3    2008_4    2008      Mumbai  20-04-2008       MI      RCB          MI
4    2008_5    2008     Kolkata  20-04-2008       DC      KKR          DC
5    2008_6    2008      Jaipur  21-04-2008      KXI       RR         KXI
6    2008_7    2008   Hyderabad  22-04-2008       DC       DD          DC
7    2008_8    2008     Chennai  23-04-2008      CSK       MI          MI
8    2008_9    2008   Hyderabad  24-04-2008       DC       RR          RR
9   2008_10    2008  Chandigarh  25-04-2008      KXI       MI          MI
10  2008_11    2008   Bangalore  26-04-2008      RCB       RR          RR
11  2008_12    2008     Chennai  26-04-2008      KKR      CSK         KKR
12  2008_13    2008      Mumbai  27-04-2008       MI       DC          DC
13  2008_14    2008  Chandigarh  27-04-2008       DD      KXI          DD
14  2008_15    2008   Bangalore  28-04-2008      CSK      RCB         CSK
15  2008_16    2008     Kolkata  29-04-2008      KKR       MI         KKR
16  2008_17    2008       Delhi  30-04-2008       DD      RCB         RCB
17  2008_18    2008   Hyderabad  01-05-2008       DC      KXI         KXI
18  2008_19    2008      Jaipur  01-05-2008       RR      KKR          RR
19  2008_20    2008     Chennai  02-05-2008      CSK       DD         CSK
20  2008_21    2008   Hyderabad  25-05-2008       DC      RCB          DC
21  2008_22    2008  Chandigarh  03-05-2008      KXI      KKR         KXI
22  2008_23    2008      Mumbai  04-05-2008       MI       DD          DD
23  2008_24    2008      Jaipur  04-05-2008      CSK       RR         CSK
24  2008_25    2008   Bangalore  05-05-2008      RCB      KXI         KXI
25  2008_26    2008     Chennai  06-05-2008      CSK       DC          DC
26  2008_27    2008      Mumbai  07-05-2008       RR       MI          MI
27  2008_28    2008       Delhi  08-05-2008       DD      CSK         CSK
28  2008_29    2008     Kolkata  08-05-2008      KKR      RCB         KKR
29  2008_30    2008      Jaipur  09-05-2008       DC       RR          RR
..      ...     ...         ...         ...      ...      ...         ...
29  2017_30    2017   Bangalore  27-04-2017      RCB       GL          GL
30  2017_31    2017     Kolkata  28-04-2017       DD      KKR         KKR
31  2017_32    2017  Chandigarh  28-04-2017      SRH      KXI         KXI
32  2017_33    2017        Pune  29-04-2017      RPS      RCB         RCB
33  2017_34    2017      Rajkot  29-04-2017       GL       MI          GL
34  2017_35    2017  Chandigarh  30-04-2017       DD      KXI         KXI
35  2017_36    2017   Hyderabad  30-04-2017      SRH      KKR         KKR
36  2017_37    2017      Mumbai  01-05-2017      RCB       MI         RCB
37  2017_38    2017        Pune  01-05-2017       GL      RPS         RPS
38  2017_39    2017       Delhi  02-05-2017      SRH       DD          DD
39  2017_40    2017     Kolkata  03-05-2017      KKR      RPS         RPS
40  2017_41    2017       Delhi  04-05-2017       GL       DD          DD
41  2017_42    2017   Bangalore  05-05-2017      KXI      RCB         RCB
42  2017_43    2017   Hyderabad  06-05-2017      RPS      SRH         SRH
43  2017_44    2017       Delhi  06-05-2017       MI       DD          DD
44  2017_45    2017   Bangalore  07-05-2017      RCB      KKR         KKR
45  2017_46    2017  Chandigarh  07-05-2017      KXI       GL          GL
46  2017_47    2017   Hyderabad  08-05-2017       MI      SRH          MI
47  2017_48    2017  Chandigarh  09-05-2017      KXI      KKR         KKR
48  2017_49    2017      Kanpur  10-05-2017       GL       DD          DD
49  2017_50    2017      Mumbai  11-05-2017      KXI       MI          MI
50  2017_51    2017       Delhi  12-05-2017       DD      RPS          DD
51  2017_52    2017      Kanpur  13-05-2017       GL      SRH         SRH
52  2017_53    2017     Kolkata  13-05-2017       MI      KKR         KKR
53  2017_54    2017        Pune  14-05-2017      KXI      RPS         RPS
54  2017_55    2017       Delhi  14-05-2017      RCB       DD         RCB
55  2017_56    2017      Mumbai  16-05-2017      RPS       MI          MI
56  2017_57    2017   Bangalore  17-05-2017      SRH      KKR         KKR
57  2017_58    2017   Bangalore  19-05-2017      KKR       MI          MI
58  2017_59    2017   Hyderabad  21-05-2017       MI      RPS          MI

   toss_decision  result  dl_applied winner  win_by_runs  win_by_wickets  \
0          field  normal           0    KKR          140               0
1            bat  normal           0    CSK           33               0
2            bat  normal           0     DD            0               9
3            bat  normal           0    RCB            0               5
4            bat  normal           0    KKR            0               5
5            bat  normal           0     RR            0               6
6            bat  normal           0     DD            0               9
7          field  normal           0    CSK            6               0
8          field  normal           0     RR            0               3
9          field  normal           0    KXI           66               0
10         field  normal           0     RR            0               7
11           bat  normal           0    CSK            0               9
12         field  normal           0     DC            0              10
13           bat  normal           0    KXI            0               4
14           bat  normal           0    CSK           13               0
15           bat  normal           0     MI            0               7
16         field  normal           0     DD           10               0
17         field  normal           0    KXI            0               7
18           bat  normal           0     RR           45               0
19           bat  normal           0     DD            0               8
20           bat  normal           0    RCB            0               5
21           bat  normal           0    KXI            9               0
22         field  normal           0     MI           29               0
23           bat  normal           0     RR            0               8
24         field  normal           0    KXI            0               6
25         field  normal           0     DC            0               7
26         field  normal           0     MI            0               7
27         field  normal           0    CSK            0               4
28           bat  normal           0    KKR            5               0
29         field  normal           0     RR            0               8
..           ...     ...         ...    ...          ...             ...
29         field  normal           0     GL            0               7
30         field  normal           0    KKR            0               7
31         field  normal           0    SRH           26               0
32         field  normal           0    RPS           61               0
33           bat     tie           0     MI            0               0
34         field  normal           0    KXI            0              10
35         field  normal           0    SRH           48               0
36           bat  normal           0     MI            0               5
37         field  normal           0    RPS            0               5
38         field  normal           0     DD            0               6
39         field  normal           0    RPS            0               4
40         field  normal           0     DD            0               7
41         field  normal           0    KXI           19               0
42         field  normal           0    RPS           12               0
43         field  normal           0     MI          146               0
44         field  normal           0    KKR            0               6
45         field  normal           0     GL            0               6
46           bat  normal           0    SRH            0               7
47         field  normal           0    KXI           14               0
48         field  normal           0     DD            0               2
49         field  normal           0    KXI            7               0
50           bat  normal           0     DD            7               0
51         field  normal           0    SRH            0               8
52         field  normal           0     MI            9               0
53         field  normal           0    RPS            0               9
54           bat  normal           0    RCB           10               0
55         field  normal           0    RPS           20               0
56         field  normal           1    KKR            0               7
57         field  normal           0     MI            0               6
58           bat  normal           0     MI            1               0

         player_of_match  player_of_match_id  \
0       Brendon McCullum                82.0
1         Michael Hussey                18.0
2       Farveez Maharoof                60.0
3           Mark Boucher               145.0
4           David Hussey                80.0
5           Shane Watson               175.0
6        Virender Sehwag                46.0
7         Matthew Hayden                 6.0
8           Yusuf Pathan               171.0
9       Kumar Sangakkara                98.0
10          Shane Watson               175.0
11            Jacob Oram                23.0
12        Adam Gilchrist                28.0
13          Simon Katich               105.0
14  Mahendra Singh Dhoni                 1.0
15     Sanath Jayasuriya               117.0
16         Glenn McGrath                50.0
17           Shaun Marsh               106.0
18      Swapnil Asnodkar               166.0
19       Virender Sehwag                46.0
20           Vinay Kumar               153.0
21          Irfan Pathan                96.0
22         Shaun Pollock               121.0
23         Sohail Tanvir               174.0
24           S Sreesanth               100.0
25        Adam Gilchrist                28.0
26          Ashish Nehra               119.0
27  Mahendra Singh Dhoni                 1.0
28        Sourav Ganguly                66.0
29          Yusuf Pathan               171.0
..                   ...                 ...
29            Andrew Tye               535.0
30        Gautam Gambhir                58.0
31           Rashid Khan               634.0
32       Lockie Ferguson               627.0
33         Krunal Pandya               582.0
34        Sandeep Sharma               479.0
35          David Warner               207.0
36          Rohit Sharma                30.0
37            Ben Stokes               625.0
38        Mohammed Shami               647.0
39        Rahul Tripathi               630.0
40          Rishabh Pant               572.0
41        Sandeep Sharma               479.0
42        Jaydev Unadkat               361.0
43         Lendl Simmons               524.0
44          Sunil Narine               437.0
45          Dwayne Smith               124.0
46        Shikhar Dhawan                57.0
47          Mohit Sharma               469.0
48          Shreyas Iyer               537.0
49       Wriddhiman Saha                84.0
50            Karun Nair               458.0
51        Mohammed Siraj               681.0
52         Ambati Rayudu               309.0
53        Jaydev Unadkat               361.0
54         Harshal Patel               456.0
55     Washington Sunder               631.0
56   Nathan Coulter-Nile               484.0
57           Karn Sharma               254.0
58         Krunal Pandya               582.0

                                                venue  venue_id  \
0          M.Chinnaswamy Stadium Bengaluru, Karnataka         7
1   I.S. Bindra Punjab Cricket Association Stadium...         9
2                     Feroz Shah Kotla Stadium, Delhi         2
3               Wankhede Stadium, Mumbai, Maharashtra         1
4           Eden Garden Stadium, Kolkata, West Bengal         3
5          Sawai Man Singh Stadium, Jaipur, Rajasthan         6
6       Rajiv Gandhi International Stadium, Hyderabad         4
7         M.A.Chidambaram Stadium Chennai, Tamil Nadu         5
8       Rajiv Gandhi International Stadium, Hyderabad         4
9   I.S. Bindra Punjab Cricket Association Stadium...         9
10         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
11        M.A.Chidambaram Stadium Chennai, Tamil Nadu         5
12                         Dr DY Patil Sports Academy        10
13  I.S. Bindra Punjab Cricket Association Stadium...         9
14         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
15          Eden Garden Stadium, Kolkata, West Bengal         3
16                    Feroz Shah Kotla Stadium, Delhi         2
17      Rajiv Gandhi International Stadium, Hyderabad         4
18         Sawai Man Singh Stadium, Jaipur, Rajasthan         6
19        M.A.Chidambaram Stadium Chennai, Tamil Nadu         5
20      Rajiv Gandhi International Stadium, Hyderabad         4
21  I.S. Bindra Punjab Cricket Association Stadium...         9
22                         Dr DY Patil Sports Academy        10
23         Sawai Man Singh Stadium, Jaipur, Rajasthan         6
24         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
25        M.A.Chidambaram Stadium Chennai, Tamil Nadu         5
26                         Dr DY Patil Sports Academy        10
27                    Feroz Shah Kotla Stadium, Delhi         2
28          Eden Garden Stadium, Kolkata, West Bengal         3
29         Sawai Man Singh Stadium, Jaipur, Rajasthan         6
..                                                ...       ...
29         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
30          Eden Garden Stadium, Kolkata, West Bengal         3
31  I.S. Bindra Punjab Cricket Association Stadium...         9
32            Maharashtra Cricket Association Stadium        32
33             Saurashtra Cricket Association Stadium        33
34  I.S. Bindra Punjab Cricket Association Stadium...         9
35      Rajiv Gandhi International Stadium, Hyderabad         4
36              Wankhede Stadium, Mumbai, Maharashtra         1
37            Maharashtra Cricket Association Stadium        32
38                    Feroz Shah Kotla Stadium, Delhi         2
39          Eden Garden Stadium, Kolkata, West Bengal         3
40                    Feroz Shah Kotla Stadium, Delhi         2
41         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
42      Rajiv Gandhi International Stadium, Hyderabad         4
43                    Feroz Shah Kotla Stadium, Delhi         2
44         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
45  I.S. Bindra Punjab Cricket Association Stadium...         9
46      Rajiv Gandhi International Stadium, Hyderabad         4
47  I.S. Bindra Punjab Cricket Association Stadium...         9
48                                         Green Park        34
49              Wankhede Stadium, Mumbai, Maharashtra         1
50                    Feroz Shah Kotla Stadium, Delhi         2
51                                         Green Park        34
52          Eden Garden Stadium, Kolkata, West Bengal         3
53            Maharashtra Cricket Association Stadium        32
54                    Feroz Shah Kotla Stadium, Delhi         2
55              Wankhede Stadium, Mumbai, Maharashtra         1
56         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
57         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
58      Rajiv Gandhi International Stadium, Hyderabad         4

                  umpire1         umpire2
0               Asad Rauf     RE Koertzen
1               MR Benson      SL Shastri
2               Aleem Dar  GA Pratapkumar
3                SJ Davis       DJ Harper
4               BF Bowden     K Hariharan
5               Aleem Dar       RB Tiffin
6               IL Howell       AM Saheba
7               DJ Harper  GA Pratapkumar
8               Asad Rauf       MR Benson
9               Aleem Dar       AM Saheba
10              MR Benson       IL Howell
11              BF Bowden  AV Jayaprakash
12              Asad Rauf      SL Shastri
13            RE Koertzen       I Shivram
14            BR Doctrove       RB Tiffin
15              BF Bowden  AV Jayaprakash
16              Aleem Dar       I Shivram
17            BR Doctrove       RB Tiffin
18            RE Koertzen  GA Pratapkumar
19              BF Bowden     K Hariharan
20              Asad Rauf     RE Koertzen
21              DJ Harper       I Shivram
22              IL Howell     RE Koertzen
23              Asad Rauf  AV Jayaprakash
24               SJ Davis     BR Doctrove
25              MR Benson       RB Tiffin
26              DJ Harper     RE Koertzen
27              Aleem Dar       RB Tiffin
28              Asad Rauf       IL Howell
29              MR Benson       AM Saheba
..                    ...             ...
29           AK Chaudhary   C Shamshuddin
30               NJ Llong          S Ravi
31            Nitin Menon       CK Nandan
32  KN Ananthapadmanabhan       M Erasmus
33           AK Chaudhary     CB Gaffaney
34               YC Barde       CK Nandan
35            AY Dandekar          S Ravi
36           AK Chaudhary     CB Gaffaney
37              M Erasmus   C Shamshuddin
38               YC Barde     Nitin Menon
39  KN Ananthapadmanabhan  A Nand Kishore
40              M Erasmus     Nitin Menon
41            CB Gaffaney   C Shamshuddin
42  KN Ananthapadmanabhan    AK Chaudhary
43            Nitin Menon       CK Nandan
44            AY Dandekar   C Shamshuddin
45         A Nand Kishore       VK Sharma
46  KN Ananthapadmanabhan       M Erasmus
47         A Nand Kishore          S Ravi
48               YC Barde    AK Chaudhary
49             A Deshmukh  A Nand Kishore
50  KN Ananthapadmanabhan       CK Nandan
51           AK Chaudhary     Nitin Menon
52         A Nand Kishore          S Ravi
53            AY Dandekar      A Deshmukh
54              CK Nandan   C Shamshuddin
55                 S Ravi   C Shamshuddin
56           AK Chaudhary     Nitin Menon
57               NJ Llong     Nitin Menon
58               NJ Llong          S Ravi

[636 rows x 19 columns]>

In [52]:
print(ipl_final.columns)

Index(['match_id', 'season', 'city', 'date', 'team1_id', 'team2_id',
       'toss_winner', 'toss_decision', 'result', 'dl_applied', 'winner',
       'win_by_runs', 'win_by_wickets', 'player_of_match',
       'player_of_match_id', 'venue', 'venue_id', 'umpire1', 'umpire2'],
      dtype='object')

In [53]:
print(ipl_final.head(1))

  match_id  season       city        date team1_id team2_id toss_winner  \
0   2008_1    2008  Bangalore  18-04-2008      KKR      RCB         RCB

  toss_decision  result  dl_applied winner  win_by_runs  win_by_wickets  \
0         field  normal           0    KKR          140               0

    player_of_match  player_of_match_id  \
0  Brendon McCullum                82.0

                                        venue  venue_id    umpire1  \
0  M.Chinnaswamy Stadium Bengaluru, Karnataka         7  Asad Rauf

       umpire2
0  RE Koertzen

In [54]:
print(ipl_final.dtypes)

match_id               object
season                  int64
city                   object
date                   object
team1_id               object
team2_id               object
toss_winner            object
toss_decision          object
result                 object
dl_applied              int64
winner                 object
win_by_runs             int64
win_by_wickets          int64
player_of_match        object
player_of_match_id    float64
venue                  object
venue_id                int64
umpire1                object
umpire2                object
dtype: object

In [60]:
ipl_final['city'] = ipl_final['city'].astype('category')

In [61]:
print(ipl_final.dtypes)

match_id                object
season                   int64
city                  category
date                    object
team1_id                object
team2_id                object
toss_winner             object
toss_decision           object
result                  object
dl_applied               int64
winner                  object
win_by_runs              int64
win_by_wickets           int64
player_of_match         object
player_of_match_id     float64
venue                   object
venue_id                 int64
umpire1                 object
umpire2                 object
dtype: object

In [ ]:
d1 =[10,20,30,40,50]

In [16]:
import pandas as pd
d1 = [10, 20, 30, 40, 50]
df = pd.DataFrame(d1)
print (df)

    0
0  10
1  20
2  30
3  40
4  50