In [83]:
import pandas as pd
import numpy as np

In [84]:
ipl_new = pd.read_csv("matches2017.csv")
ipl = pd.read_csv("matches2008-2016.csv")

In [85]:
ipl.shape

(577, 19)

In [86]:
ipl_new.shape

(59, 19)

In [87]:
matches = ipl.append(ipl_new,ignore_index=True)

In [88]:
matches.head(5)
matches.shape

(636, 19)

In [89]:
matches.dtypes

match_id               object
season                  int64
city                   object
date                   object
team1_id               object
team2_id               object
toss_winner            object
toss_decision          object
result                 object
dl_applied              int64
winner                 object
win_by_runs             int64
win_by_wickets          int64
player_of_match        object
player_of_match_id    float64
venue                  object
venue_id                int64
umpire1                object
umpire2                object
dtype: object

In [90]:
matches.city = matches.city.astype('category')

In [91]:
matches.dtypes

match_id                object
season                   int64
city                  category
date                    object
team1_id                object
team2_id                object
toss_winner             object
toss_decision           object
result                  object
dl_applied               int64
winner                  object
win_by_runs              int64
win_by_wickets           int64
player_of_match         object
player_of_match_id     float64
venue                   object
venue_id                 int64
umpire1                 object
umpire2                 object
dtype: object

In [92]:
matches[['team1_id','team2_id','toss_winner','toss_decision','result','winner','player_of_match_id','venue','venue_id','umpire1','umpire2']] = \
    matches[['team1_id','team2_id','toss_winner','toss_decision','result','winner','player_of_match_id','venue','venue_id','umpire1','umpire2']].astype('category')

In [93]:
matches.dtypes

match_id                object
season                   int64
city                  category
date                    object
team1_id              category
team2_id              category
toss_winner           category
toss_decision         category
result                category
dl_applied               int64
winner                category
win_by_runs              int64
win_by_wickets           int64
player_of_match         object
player_of_match_id    category
venue                 category
venue_id              category
umpire1               category
umpire2               category
dtype: object

In [94]:
matches.describe()

            season  dl_applied  win_by_runs  win_by_wickets
count   636.000000  636.000000   636.000000      636.000000
mean   2012.490566    0.025157    13.682390        3.372642
std       2.773026    0.156726    23.908877        3.420338
min    2008.000000    0.000000     0.000000        0.000000
25%    2010.000000    0.000000     0.000000        0.000000
50%    2012.000000    0.000000     0.000000        4.000000
75%    2015.000000    0.000000    20.000000        7.000000
max    2017.000000    1.000000   146.000000       10.000000

In [95]:
matches.venue_id.value_counts()

7     66
3     61
2     60
1     57
4     49
5     48
9     46
6     33
26    17
10    17
32    15
13    15
14    12
20    12
19    11
25    11
33    10
23     9
16     8
28     7
29     7
21     7
12     7
11     7
31     7
30     6
27     6
8      5
24     5
34     4
15     3
22     3
17     3
18     2
Name: venue_id, dtype: int64

In [96]:
matches.isnull().sum()

match_id              0
season                0
city                  7
date                  0
team1_id              0
team2_id              0
toss_winner           0
toss_decision         0
result                0
dl_applied            0
winner                3
win_by_runs           0
win_by_wickets        0
player_of_match       3
player_of_match_id    3
venue                 0
venue_id              0
umpire1               1
umpire2               1
dtype: int64

In [98]:
matches.iloc[:,1:19]

,season,city,date,team1_id,team2_id,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,player_of_match_id,venue,venue_id,umpire1,umpire2
0,2008,Bangalore,18-04-2008,KKR,RCB,RCB,field,normal,0,KKR,140,0,Brendon McCullum,82.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,Asad Rauf,RE Koertzen
1,2008,Chandigarh,19-04-2008,CSK,KXI,CSK,bat,normal,0,CSK,33,0,Michael Hussey,18.0,I.S. Bindra Punjab Cricket Association Stadium...,9,MR Benson,SL Shastri
2,2008,Delhi,19-04-2008,RR,DD,RR,bat,normal,0,DD,0,9,Farveez Maharoof,60.0,"Feroz Shah Kotla Stadium, Delhi",2,Aleem Dar,GA Pratapkumar
3,2008,Mumbai,20-04-2008,MI,RCB,MI,bat,normal,0,RCB,0,5,Mark Boucher,145.0,"Wankhede Stadium, Mumbai, Maharashtra",1,SJ Davis,DJ Harper
4,2008,Kolkata,20-04-2008,DC,KKR,DC,bat,normal,0,KKR,0,5,David Hussey,80.0,"Eden Garden Stadium, Kolkata, West Bengal",3,BF Bowden,K Hariharan
5,2008,Jaipur,21-04-2008,KXI,RR,KXI,bat,normal,0,RR,0,6,Shane Watson,175.0,"Sawai Man Singh Stadium, Jaipur, Rajasthan",6,Aleem Dar,RB Tiffin
6,2008,Hyderabad,22-04-2008,DC,DD,DC,bat,normal,0,DD,0,9,Virender Sehwag,46.0,"Rajiv Gandhi International Stadium, Hyderabad",4,IL Howell,AM Saheba
7,2008,Chennai,23-04-2008,CSK,MI,MI,field,normal,0,CSK,6,0,Matthew Hayden,6.0,"M.A.Chidambaram Stadium Chennai, Tamil Nadu",5,DJ Harper,GA Pratapkumar
8,2008,Hyderabad,24-04-2008,DC,RR,RR,field,normal,0,RR,0,3,Yusuf Pathan,171.0,"Rajiv Gandhi International Stadium, Hyderabad",4,Asad Rauf,MR Benson
9,2008,Chandigarh,25-04-2008,KXI,MI,MI,field,normal,0,KXI,66,0,Kumar Sangakkara,98.0,I.S. Bindra Punjab Cricket Association Stadium...,9,Aleem Dar,AM Saheba
10,2008,Bangalore,26-04-2008,RCB,RR,RR,field,normal,0,RR,0,7,Shane Watson,175.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,MR Benson,IL Howell
11,2008,Chennai,26-04-2008,KKR,CSK,KKR,bat,normal,0,CSK,0,9,Jacob Oram,23.0,"M.A.Chidambaram Stadium Chennai, Tamil Nadu",5,BF Bowden,AV Jayaprakash
12,2008,Mumbai,27-04-2008,MI,DC,DC,field,normal,0,DC,0,10,Adam Gilchrist,28.0,Dr DY Patil Sports Academy,10,Asad Rauf,SL Shastri
13,2008,Chandigarh,27-04-2008,DD,KXI,DD,bat,normal,0,KXI,0,4,Simon Katich,105.0,I.S. Bindra Punjab Cricket Association Stadium...,9,RE Koertzen,I Shivram
14,2008,Bangalore,28-04-2008,CSK,RCB,CSK,bat,normal,0,CSK,13,0,Mahendra Singh Dhoni,1.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,BR Doctrove,RB Tiffin
15,2008,Kolkata,29-04-2008,KKR,MI,KKR,bat,normal,0,MI,0,7,Sanath Jayasuriya,117.0,"Eden Garden Stadium, Kolkata, West Bengal",3,BF Bowden,AV Jayaprakash
16,2008,Delhi,30-04-2008,DD,RCB,RCB,field,normal,0,DD,10,0,Glenn McGrath,50.0,"Feroz Shah Kotla Stadium, Delhi",2,Aleem Dar,I Shivram
17,2008,Hyderabad,01-05-2008,DC,KXI,KXI,field,normal,0,KXI,0,7,Shaun Marsh,106.0,"Rajiv Gandhi International Stadium, Hyderabad",4,BR Doctrove,RB Tiffin
18,2008,Jaipur,01-05-2008,RR,KKR,RR,bat,normal,0,RR,45,0,Swapnil Asnodkar,166.0,"Sawai Man Singh Stadium, Jaipur, Rajasthan",6,RE Koertzen,GA Pratapkumar
19,2008,Chennai,02-05-2008,CSK,DD,CSK,bat,normal,0,DD,0,8,Virender Sehwag,46.0,"M.A.Chidambaram Stadium Chennai, Tamil Nadu",5,BF Bowden,K Hariharan
20,2008,Hyderabad,25-05-2008,DC,RCB,DC,bat,normal,0,RCB,0,5,Vinay Kumar,153.0,"Rajiv Gandhi International Stadium, Hyderabad",4,Asad Rauf,RE Koertzen
21,2008,Chandigarh,03-05-2008,KXI,KKR,KXI,bat,normal,0,KXI,9,0,Irfan Pathan,96.0,I.S. Bindra Punjab Cricket Association Stadium...,9,DJ Harper,I Shivram
22,2008,Mumbai,04-05-2008,MI,DD,DD,field,normal,0,MI,29,0,Shaun Pollock,121.0,Dr DY Patil Sports Academy,10,IL Howell,RE Koertzen
23,2008,Jaipur,04-05-2008,CSK,RR,CSK,bat,normal,0,RR,0,8,Sohail Tanvir,174.0,"Sawai Man Singh Stadium, Jaipur, Rajasthan",6,Asad Rauf,AV Jayaprakash
24,2008,Bangalore,05-05-2008,RCB,KXI,KXI,field,normal,0,KXI,0,6,S Sreesanth,100.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,SJ Davis,BR Doctrove
25,2008,Chennai,06-05-2008,CSK,DC,DC,field,normal,0,DC,0,7,Adam Gilchrist,28.0,"M.A.Chidambaram Stadium Chennai, Tamil Nadu",5,MR Benson,RB Tiffin
26,2008,Mumbai,07-05-2008,RR,MI,MI,field,normal,0,MI,0,7,Ashish Nehra,119.0,Dr DY Patil Sports Academy,10,DJ Harper,RE Koertzen
27,2008,Delhi,08-05-2008,DD,CSK,CSK,field,normal,0,CSK,0,4,Mahendra Singh Dhoni,1.0,"Feroz Shah Kotla Stadium, Delhi",2,Aleem Dar,RB Tiffin
28,2008,Kolkata,08-05-2008,KKR,RCB,KKR,bat,normal,0,KKR,5,0,Sourav Ganguly,66.0,"Eden Garden Stadium, Kolkata, West Bengal",3,Asad Rauf,IL Howell
29,2008,Jaipur,09-05-2008,DC,RR,RR,field,normal,0,RR,0,8,Yusuf Pathan,171.0,"Sawai Man Singh Stadium, Jaipur, Rajasthan",6,MR Benson,AM Saheba
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2017,Bangalore,27-04-2017,RCB,GL,GL,field,normal,0,GL,0,7,Andrew Tye,535.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,AK Chaudhary,C Shamshuddin
607,2017,Kolkata,28-04-2017,DD,KKR,KKR,field,normal,0,KKR,0,7,Gautam Gambhir,58.0,"Eden Garden Stadium, Kolkata, West Bengal",3,NJ Llong,S Ravi
608,2017,Chandigarh,28-04-2017,SRH,KXI,KXI,field,normal,0,SRH,26,0,Rashid Khan,634.0,I.S. Bindra Punjab Cricket Association Stadium...,9,Nitin Menon,CK Nandan
609,2017,Pune,29-04-2017,RPS,RCB,RCB,field,normal,0,RPS,61,0,Lockie Ferguson,627.0,Maharashtra Cricket Association Stadium,32,KN Ananthapadmanabhan,M Erasmus
610,2017,Rajkot,29-04-2017,GL,MI,GL,bat,tie,0,MI,0,0,Krunal Pandya,582.0,Saurashtra Cricket Association Stadium,33,AK Chaudhary,CB Gaffaney
611,2017,Chandigarh,30-04-2017,DD,KXI,KXI,field,normal,0,KXI,0,10,Sandeep Sharma,479.0,I.S. Bindra Punjab Cricket Association Stadium...,9,YC Barde,CK Nandan
612,2017,Hyderabad,30-04-2017,SRH,KKR,KKR,field,normal,0,SRH,48,0,David Warner,207.0,"Rajiv Gandhi International Stadium, Hyderabad",4,AY Dandekar,S Ravi
613,2017,Mumbai,01-05-2017,RCB,MI,RCB,bat,normal,0,MI,0,5,Rohit Sharma,30.0,"Wankhede Stadium, Mumbai, Maharashtra",1,AK Chaudhary,CB Gaffaney
614,2017,Pune,01-05-2017,GL,RPS,RPS,field,normal,0,RPS,0,5,Ben Stokes,625.0,Maharashtra Cricket Association Stadium,32,M Erasmus,C Shamshuddin
615,2017,Delhi,02-05-2017,SRH,DD,DD,field,normal,0,DD,0,6,Mohammed Shami,647.0,"Feroz Shah Kotla Stadium, Delhi",2,YC Barde,Nitin Menon
616,2017,Kolkata,03-05-2017,KKR,RPS,RPS,field,normal,0,RPS,0,4,Rahul Tripathi,630.0,"Eden Garden Stadium, Kolkata, West Bengal",3,KN Ananthapadmanabhan,A Nand Kishore
617,2017,Delhi,04-05-2017,GL,DD,DD,field,normal,0,DD,0,7,Rishabh Pant,572.0,"Feroz Shah Kotla Stadium, Delhi",2,M Erasmus,Nitin Menon
618,2017,Bangalore,05-05-2017,KXI,RCB,RCB,field,normal,0,KXI,19,0,Sandeep Sharma,479.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,CB Gaffaney,C Shamshuddin
619,2017,Hyderabad,06-05-2017,RPS,SRH,SRH,field,normal,0,RPS,12,0,Jaydev Unadkat,361.0,"Rajiv Gandhi International Stadium, Hyderabad",4,KN Ananthapadmanabhan,AK Chaudhary
620,2017,Delhi,06-05-2017,MI,DD,DD,field,normal,0,MI,146,0,Lendl Simmons,524.0,"Feroz Shah Kotla Stadium, Delhi",2,Nitin Menon,CK Nandan
621,2017,Bangalore,07-05-2017,RCB,KKR,KKR,field,normal,0,KKR,0,6,Sunil Narine,437.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,AY Dandekar,C Shamshuddin
622,2017,Chandigarh,07-05-2017,KXI,GL,GL,field,normal,0,GL,0,6,Dwayne Smith,124.0,I.S. Bindra Punjab Cricket Association Stadium...,9,A Nand Kishore,VK Sharma
623,2017,Hyderabad,08-05-2017,MI,SRH,MI,bat,normal,0,SRH,0,7,Shikhar Dhawan,57.0,"Rajiv Gandhi International Stadium, Hyderabad",4,KN Ananthapadmanabhan,M Erasmus
624,2017,Chandigarh,09-05-2017,KXI,KKR,KKR,field,normal,0,KXI,14,0,Mohit Sharma,469.0,I.S. Bindra Punjab Cricket Association Stadium...,9,A Nand Kishore,S Ravi
625,2017,Kanpur,10-05-2017,GL,DD,DD,field,normal,0,DD,0,2,Shreyas Iyer,537.0,Green Park,34,YC Barde,AK Chaudhary
626,2017,Mumbai,11-05-2017,KXI,MI,MI,field,normal,0,KXI,7,0,Wriddhiman Saha,84.0,"Wankhede Stadium, Mumbai, Maharashtra",1,A Deshmukh,A Nand Kishore
627,2017,Delhi,12-05-2017,DD,RPS,DD,bat,normal,0,DD,7,0,Karun Nair,458.0,"Feroz Shah Kotla Stadium, Delhi",2,KN Ananthapadmanabhan,CK Nandan
628,2017,Kanpur,13-05-2017,GL,SRH,SRH,field,normal,0,SRH,0,8,Mohammed Siraj,681.0,Green Park,34,AK Chaudhary,Nitin Menon
629,2017,Kolkata,13-05-2017,MI,KKR,KKR,field,normal,0,MI,9,0,Ambati Rayudu,309.0,"Eden Garden Stadium, Kolkata, West Bengal",3,A Nand Kishore,S Ravi
630,2017,Pune,14-05-2017,KXI,RPS,RPS,field,normal,0,RPS,0,9,Jaydev Unadkat,361.0,Maharashtra Cricket Association Stadium,32,AY Dandekar,A Deshmukh
631,2017,Delhi,14-05-2017,RCB,DD,RCB,bat,normal,0,RCB,10,0,Harshal Patel,456.0,"Feroz Shah Kotla Stadium, Delhi",2,CK Nandan,C Shamshuddin
632,2017,Mumbai,16-05-2017,RPS,MI,MI,field,normal,0,RPS,20,0,Washington Sunder,631.0,"Wankhede Stadium, Mumbai, Maharashtra",1,S Ravi,C Shamshuddin
633,2017,Bangalore,17-05-2017,SRH,KKR,KKR,field,normal,1,KKR,0,7,Nathan Coulter-Nile,484.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,AK Chaudhary,Nitin Menon
634,2017,Bangalore,19-05-2017,KKR,MI,MI,field,normal,0,MI,0,6,Karn Sharma,254.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,NJ Llong,Nitin Menon
635,2017,Hyderabad,21-05-2017,MI,RPS,MI,bat,normal,0,MI,1,0,Krunal Pandya,582.0,"Rajiv Gandhi International Stadium, Hyderabad",4,NJ Llong,S Ravi

In [99]:
maches_venue_id = pd.get_dummies(matches['venue_id'])

In [100]:
matches = matches.join(maches_venue_id)

In [101]:
maches_venue_id

,1,2,3,4,5,6,7,8,9,10,...,25,26,27,28,29,30,31,32,33,34
0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
27,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
607,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
608,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
609,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
610,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
611,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
612,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
613,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
614,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
615,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
616,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
617,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
618,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
619,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
620,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
621,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
622,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
623,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
624,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
625,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
626,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
627,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
628,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
629,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
630,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
631,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
632,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
633,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
634,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
635,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [102]:
matches = matches.drop('venue_id',axis =1)

In [103]:
matches.head(6)

,match_id,season,city,date,team1_id,team2_id,toss_winner,toss_decision,result,dl_applied,...,25,26,27,28,29,30,31,32,33,34
0,2008_1,2008,Bangalore,18-04-2008,KKR,RCB,RCB,field,normal,0,...,0,0,0,0,0,0,0,0,0,0
1,2008_2,2008,Chandigarh,19-04-2008,CSK,KXI,CSK,bat,normal,0,...,0,0,0,0,0,0,0,0,0,0
2,2008_3,2008,Delhi,19-04-2008,RR,DD,RR,bat,normal,0,...,0,0,0,0,0,0,0,0,0,0
3,2008_4,2008,Mumbai,20-04-2008,MI,RCB,MI,bat,normal,0,...,0,0,0,0,0,0,0,0,0,0
4,2008_5,2008,Kolkata,20-04-2008,DC,KKR,DC,bat,normal,0,...,0,0,0,0,0,0,0,0,0,0
5,2008_6,2008,Jaipur,21-04-2008,KXI,RR,KXI,bat,normal,0,...,0,0,0,0,0,0,0,0,0,0

In [105]:
matches.iloc[:,1:19] = matches.iloc[:,1:19].replace('',np.nan)

In [106]:
matches.isna().sum()

match_id              0
season                0
city                  7
date                  0
team1_id              0
team2_id              0
toss_winner           0
toss_decision         0
result                0
dl_applied            0
winner                3
win_by_runs           0
win_by_wickets        0
player_of_match       3
player_of_match_id    3
venue                 0
umpire1               1
umpire2               1
1                     0
2                     0
3                     0
4                     0
5                     0
6                     0
7                     0
8                     0
9                     0
10                    0
11                    0
12                    0
13                    0
14                    0
15                    0
16                    0
17                    0
18                    0
19                    0
20                    0
21                    0
22                    0
23                    0
24                    0
25                    0
26                    0
27                    0
28                    0
29                    0
30                    0
31                    0
32                    0
33                    0
34                    0
dtype: int64

In [110]:
matches[404:410]

,match_id,season,city,date,team1_id,team2_id,toss_winner,toss_decision,result,dl_applied,...,25,26,27,28,29,30,31,32,33,34
404,2014_7,2014,Sharjah,20-04-2014,RR,KXI,KXI,field,normal,0,...,0,0,0,0,0,1,0,0,0,0
405,2014_8,2014,Abu Dhabi,21-04-2014,CSK,DD,CSK,bat,normal,0,...,0,0,0,0,1,0,0,0,0,0
406,2014_9,2014,Sharjah,22-04-2014,KXI,SRH,SRH,field,normal,0,...,0,0,0,0,0,1,0,0,0,0
407,2014_10,2014,NaN,23-04-2014,CSK,RR,RR,field,normal,0,...,0,0,0,0,0,0,1,0,0,0
408,2014_11,2014,Sharjah,24-04-2014,KKR,RCB,RCB,field,normal,0,...,0,0,0,0,0,1,0,0,0,0
409,2014_12,2014,NaN,25-04-2014,SRH,DD,SRH,bat,normal,0,...,0,0,0,0,0,0,1,0,0,0

In [111]:
matches_na_rows_dropped = matches.copy()

In [113]:
matches_na_rows_dropped = matches_na_rows_dropped.dropna(axis=0)

In [114]:
matches_na_rows_dropped.shape

(625, 52)

In [115]:
matches_na_cols_dropped = matches.copy()

In [116]:
matches_na_cols_dropped = matches_na_cols_dropped.dropna(axis=1)

In [117]:
matches_na_cols_dropped.shape

(636, 46)

In [129]:
from sklearn.preprocessing import Imputer

In [130]:
mean_imputer = Imputer(strategy="mean")

In [131]:
matches.isnull().sum()

match_id              0
season                0
city                  7
date                  0
team1_id              0
team2_id              0
toss_winner           0
toss_decision         0
result                0
dl_applied            0
winner                3
win_by_runs           0
win_by_wickets        0
player_of_match       3
player_of_match_id    3
venue                 0
umpire1               1
umpire2               1
1                     0
2                     0
3                     0
4                     0
5                     0
6                     0
7                     0
8                     0
9                     0
10                    0
11                    0
12                    0
13                    0
14                    0
15                    0
16                    0
17                    0
18                    0
19                    0
20                    0
21                    0
22                    0
23                    0
24                    0
25                    0
26                    0
27                    0
28                    0
29                    0
30                    0
31                    0
32                    0
33                    0
34                    0
dtype: int64

In [132]:
mean_imputed = matches.copy()

In [133]:
mean_imputed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 52 columns):
match_id              636 non-null object
season                636 non-null int64
city                  629 non-null category
date                  636 non-null object
team1_id              636 non-null category
team2_id              636 non-null category
toss_winner           636 non-null category
toss_decision         636 non-null category
result                636 non-null category
dl_applied            636 non-null int64
winner                633 non-null category
win_by_runs           636 non-null int64
win_by_wickets        636 non-null int64
player_of_match       633 non-null object
player_of_match_id    633 non-null category
venue                 636 non-null category
umpire1               635 non-null category
umpire2               635 non-null category
1                     636 non-null int64
2                     636 non-null uint8
3                     636 non-null uint8
4                     636 non-null uint8
5                     636 non-null uint8
6                     636 non-null uint8
7                     636 non-null uint8
8                     636 non-null uint8
9                     636 non-null uint8
10                    636 non-null uint8
11                    636 non-null uint8
12                    636 non-null uint8
13                    636 non-null uint8
14                    636 non-null uint8
15                    636 non-null uint8
16                    636 non-null uint8
17                    636 non-null uint8
18                    636 non-null uint8
19                    636 non-null uint8
20                    636 non-null uint8
21                    636 non-null uint8
22                    636 non-null uint8
23                    636 non-null uint8
24                    636 non-null uint8
25                    636 non-null uint8
26                    636 non-null uint8
27                    636 non-null uint8
28                    636 non-null uint8
29                    636 non-null uint8
30                    636 non-null uint8
31                    636 non-null uint8
32                    636 non-null uint8
33                    636 non-null uint8
34                    636 non-null uint8
dtypes: category(11), int64(5), object(3), uint8(33)
memory usage: 88.6+ KB

In [141]:
mean_imputed.loc[:,["season","dl_applied","win_by_runs","win_by_wickets"]] = mean_imputer.fit_transform(mean_imputed.loc[:,["season","dl_applied","win_by_runs","win_by_wickets"]])

In [144]:
mean_imputed.isna().sum()

match_id              0
season                0
city                  7
date                  0
team1_id              0
team2_id              0
toss_winner           0
toss_decision         0
result                0
dl_applied            0
winner                3
win_by_runs           0
win_by_wickets        0
player_of_match       3
player_of_match_id    3
venue                 0
umpire1               1
umpire2               1
1                     0
2                     0
3                     0
4                     0
5                     0
6                     0
7                     0
8                     0
9                     0
10                    0
11                    0
12                    0
13                    0
14                    0
15                    0
16                    0
17                    0
18                    0
19                    0
20                    0
21                    0
22                    0
23                    0
24                    0
25                    0
26                    0
27                    0
28                    0
29                    0
30                    0
31                    0
32                    0
33                    0
34                    0
dtype: int64