In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\Prashanth Yerabati\\Python Lab'

In [4]:
import pandas as pd
import numpy as np

In [5]:
ipl = pd.read_csv('matches2008-2016.csv')
ipl_new = pd.read_csv('matches2017.csv')
ipl_final = ipl.copy()
matches = ipl_final.append(ipl_new,ignore_index=True)
matches

,match_id,season,city,date,team1_id,team2_id,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,player_of_match_id,venue,venue_id,umpire1,umpire2
0,2008_1,2008,Bangalore,18-04-2008,KKR,RCB,RCB,field,normal,0,KKR,140,0,Brendon McCullum,82.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,Asad Rauf,RE Koertzen
1,2008_2,2008,Chandigarh,19-04-2008,CSK,KXI,CSK,bat,normal,0,CSK,33,0,Michael Hussey,18.0,I.S. Bindra Punjab Cricket Association Stadium...,9,MR Benson,SL Shastri
2,2008_3,2008,Delhi,19-04-2008,RR,DD,RR,bat,normal,0,DD,0,9,Farveez Maharoof,60.0,"Feroz Shah Kotla Stadium, Delhi",2,Aleem Dar,GA Pratapkumar
3,2008_4,2008,Mumbai,20-04-2008,MI,RCB,MI,bat,normal,0,RCB,0,5,Mark Boucher,145.0,"Wankhede Stadium, Mumbai, Maharashtra",1,SJ Davis,DJ Harper
4,2008_5,2008,Kolkata,20-04-2008,DC,KKR,DC,bat,normal,0,KKR,0,5,David Hussey,80.0,"Eden Garden Stadium, Kolkata, West Bengal",3,BF Bowden,K Hariharan
5,2008_6,2008,Jaipur,21-04-2008,KXI,RR,KXI,bat,normal,0,RR,0,6,Shane Watson,175.0,"Sawai Man Singh Stadium, Jaipur, Rajasthan",6,Aleem Dar,RB Tiffin
6,2008_7,2008,Hyderabad,22-04-2008,DC,DD,DC,bat,normal,0,DD,0,9,Virender Sehwag,46.0,"Rajiv Gandhi International Stadium, Hyderabad",4,IL Howell,AM Saheba
7,2008_8,2008,Chennai,23-04-2008,CSK,MI,MI,field,normal,0,CSK,6,0,Matthew Hayden,6.0,"M.A.Chidambaram Stadium Chennai, Tamil Nadu",5,DJ Harper,GA Pratapkumar
8,2008_9,2008,Hyderabad,24-04-2008,DC,RR,RR,field,normal,0,RR,0,3,Yusuf Pathan,171.0,"Rajiv Gandhi International Stadium, Hyderabad",4,Asad Rauf,MR Benson
9,2008_10,2008,Chandigarh,25-04-2008,KXI,MI,MI,field,normal,0,KXI,66,0,Kumar Sangakkara,98.0,I.S. Bindra Punjab Cricket Association Stadium...,9,Aleem Dar,AM Saheba
10,2008_11,2008,Bangalore,26-04-2008,RCB,RR,RR,field,normal,0,RR,0,7,Shane Watson,175.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,MR Benson,IL Howell
11,2008_12,2008,Chennai,26-04-2008,KKR,CSK,KKR,bat,normal,0,CSK,0,9,Jacob Oram,23.0,"M.A.Chidambaram Stadium Chennai, Tamil Nadu",5,BF Bowden,AV Jayaprakash
12,2008_13,2008,Mumbai,27-04-2008,MI,DC,DC,field,normal,0,DC,0,10,Adam Gilchrist,28.0,Dr DY Patil Sports Academy,10,Asad Rauf,SL Shastri
13,2008_14,2008,Chandigarh,27-04-2008,DD,KXI,DD,bat,normal,0,KXI,0,4,Simon Katich,105.0,I.S. Bindra Punjab Cricket Association Stadium...,9,RE Koertzen,I Shivram
14,2008_15,2008,Bangalore,28-04-2008,CSK,RCB,CSK,bat,normal,0,CSK,13,0,Mahendra Singh Dhoni,1.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,BR Doctrove,RB Tiffin
15,2008_16,2008,Kolkata,29-04-2008,KKR,MI,KKR,bat,normal,0,MI,0,7,Sanath Jayasuriya,117.0,"Eden Garden Stadium, Kolkata, West Bengal",3,BF Bowden,AV Jayaprakash
16,2008_17,2008,Delhi,30-04-2008,DD,RCB,RCB,field,normal,0,DD,10,0,Glenn McGrath,50.0,"Feroz Shah Kotla Stadium, Delhi",2,Aleem Dar,I Shivram
17,2008_18,2008,Hyderabad,01-05-2008,DC,KXI,KXI,field,normal,0,KXI,0,7,Shaun Marsh,106.0,"Rajiv Gandhi International Stadium, Hyderabad",4,BR Doctrove,RB Tiffin
18,2008_19,2008,Jaipur,01-05-2008,RR,KKR,RR,bat,normal,0,RR,45,0,Swapnil Asnodkar,166.0,"Sawai Man Singh Stadium, Jaipur, Rajasthan",6,RE Koertzen,GA Pratapkumar
19,2008_20,2008,Chennai,02-05-2008,CSK,DD,CSK,bat,normal,0,DD,0,8,Virender Sehwag,46.0,"M.A.Chidambaram Stadium Chennai, Tamil Nadu",5,BF Bowden,K Hariharan
20,2008_21,2008,Hyderabad,25-05-2008,DC,RCB,DC,bat,normal,0,RCB,0,5,Vinay Kumar,153.0,"Rajiv Gandhi International Stadium, Hyderabad",4,Asad Rauf,RE Koertzen
21,2008_22,2008,Chandigarh,03-05-2008,KXI,KKR,KXI,bat,normal,0,KXI,9,0,Irfan Pathan,96.0,I.S. Bindra Punjab Cricket Association Stadium...,9,DJ Harper,I Shivram
22,2008_23,2008,Mumbai,04-05-2008,MI,DD,DD,field,normal,0,MI,29,0,Shaun Pollock,121.0,Dr DY Patil Sports Academy,10,IL Howell,RE Koertzen
23,2008_24,2008,Jaipur,04-05-2008,CSK,RR,CSK,bat,normal,0,RR,0,8,Sohail Tanvir,174.0,"Sawai Man Singh Stadium, Jaipur, Rajasthan",6,Asad Rauf,AV Jayaprakash
24,2008_25,2008,Bangalore,05-05-2008,RCB,KXI,KXI,field,normal,0,KXI,0,6,S Sreesanth,100.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,SJ Davis,BR Doctrove
25,2008_26,2008,Chennai,06-05-2008,CSK,DC,DC,field,normal,0,DC,0,7,Adam Gilchrist,28.0,"M.A.Chidambaram Stadium Chennai, Tamil Nadu",5,MR Benson,RB Tiffin
26,2008_27,2008,Mumbai,07-05-2008,RR,MI,MI,field,normal,0,MI,0,7,Ashish Nehra,119.0,Dr DY Patil Sports Academy,10,DJ Harper,RE Koertzen
27,2008_28,2008,Delhi,08-05-2008,DD,CSK,CSK,field,normal,0,CSK,0,4,Mahendra Singh Dhoni,1.0,"Feroz Shah Kotla Stadium, Delhi",2,Aleem Dar,RB Tiffin
28,2008_29,2008,Kolkata,08-05-2008,KKR,RCB,KKR,bat,normal,0,KKR,5,0,Sourav Ganguly,66.0,"Eden Garden Stadium, Kolkata, West Bengal",3,Asad Rauf,IL Howell
29,2008_30,2008,Jaipur,09-05-2008,DC,RR,RR,field,normal,0,RR,0,8,Yusuf Pathan,171.0,"Sawai Man Singh Stadium, Jaipur, Rajasthan",6,MR Benson,AM Saheba
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2017_30,2017,Bangalore,27-04-2017,RCB,GL,GL,field,normal,0,GL,0,7,Andrew Tye,535.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,AK Chaudhary,C Shamshuddin
607,2017_31,2017,Kolkata,28-04-2017,DD,KKR,KKR,field,normal,0,KKR,0,7,Gautam Gambhir,58.0,"Eden Garden Stadium, Kolkata, West Bengal",3,NJ Llong,S Ravi
608,2017_32,2017,Chandigarh,28-04-2017,SRH,KXI,KXI,field,normal,0,SRH,26,0,Rashid Khan,634.0,I.S. Bindra Punjab Cricket Association Stadium...,9,Nitin Menon,CK Nandan
609,2017_33,2017,Pune,29-04-2017,RPS,RCB,RCB,field,normal,0,RPS,61,0,Lockie Ferguson,627.0,Maharashtra Cricket Association Stadium,32,KN Ananthapadmanabhan,M Erasmus
610,2017_34,2017,Rajkot,29-04-2017,GL,MI,GL,bat,tie,0,MI,0,0,Krunal Pandya,582.0,Saurashtra Cricket Association Stadium,33,AK Chaudhary,CB Gaffaney
611,2017_35,2017,Chandigarh,30-04-2017,DD,KXI,KXI,field,normal,0,KXI,0,10,Sandeep Sharma,479.0,I.S. Bindra Punjab Cricket Association Stadium...,9,YC Barde,CK Nandan
612,2017_36,2017,Hyderabad,30-04-2017,SRH,KKR,KKR,field,normal,0,SRH,48,0,David Warner,207.0,"Rajiv Gandhi International Stadium, Hyderabad",4,AY Dandekar,S Ravi
613,2017_37,2017,Mumbai,01-05-2017,RCB,MI,RCB,bat,normal,0,MI,0,5,Rohit Sharma,30.0,"Wankhede Stadium, Mumbai, Maharashtra",1,AK Chaudhary,CB Gaffaney
614,2017_38,2017,Pune,01-05-2017,GL,RPS,RPS,field,normal,0,RPS,0,5,Ben Stokes,625.0,Maharashtra Cricket Association Stadium,32,M Erasmus,C Shamshuddin
615,2017_39,2017,Delhi,02-05-2017,SRH,DD,DD,field,normal,0,DD,0,6,Mohammed Shami,647.0,"Feroz Shah Kotla Stadium, Delhi",2,YC Barde,Nitin Menon
616,2017_40,2017,Kolkata,03-05-2017,KKR,RPS,RPS,field,normal,0,RPS,0,4,Rahul Tripathi,630.0,"Eden Garden Stadium, Kolkata, West Bengal",3,KN Ananthapadmanabhan,A Nand Kishore
617,2017_41,2017,Delhi,04-05-2017,GL,DD,DD,field,normal,0,DD,0,7,Rishabh Pant,572.0,"Feroz Shah Kotla Stadium, Delhi",2,M Erasmus,Nitin Menon
618,2017_42,2017,Bangalore,05-05-2017,KXI,RCB,RCB,field,normal,0,KXI,19,0,Sandeep Sharma,479.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,CB Gaffaney,C Shamshuddin
619,2017_43,2017,Hyderabad,06-05-2017,RPS,SRH,SRH,field,normal,0,RPS,12,0,Jaydev Unadkat,361.0,"Rajiv Gandhi International Stadium, Hyderabad",4,KN Ananthapadmanabhan,AK Chaudhary
620,2017_44,2017,Delhi,06-05-2017,MI,DD,DD,field,normal,0,MI,146,0,Lendl Simmons,524.0,"Feroz Shah Kotla Stadium, Delhi",2,Nitin Menon,CK Nandan
621,2017_45,2017,Bangalore,07-05-2017,RCB,KKR,KKR,field,normal,0,KKR,0,6,Sunil Narine,437.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,AY Dandekar,C Shamshuddin
622,2017_46,2017,Chandigarh,07-05-2017,KXI,GL,GL,field,normal,0,GL,0,6,Dwayne Smith,124.0,I.S. Bindra Punjab Cricket Association Stadium...,9,A Nand Kishore,VK Sharma
623,2017_47,2017,Hyderabad,08-05-2017,MI,SRH,MI,bat,normal,0,SRH,0,7,Shikhar Dhawan,57.0,"Rajiv Gandhi International Stadium, Hyderabad",4,KN Ananthapadmanabhan,M Erasmus
624,2017_48,2017,Chandigarh,09-05-2017,KXI,KKR,KKR,field,normal,0,KXI,14,0,Mohit Sharma,469.0,I.S. Bindra Punjab Cricket Association Stadium...,9,A Nand Kishore,S Ravi
625,2017_49,2017,Kanpur,10-05-2017,GL,DD,DD,field,normal,0,DD,0,2,Shreyas Iyer,537.0,Green Park,34,YC Barde,AK Chaudhary
626,2017_50,2017,Mumbai,11-05-2017,KXI,MI,MI,field,normal,0,KXI,7,0,Wriddhiman Saha,84.0,"Wankhede Stadium, Mumbai, Maharashtra",1,A Deshmukh,A Nand Kishore
627,2017_51,2017,Delhi,12-05-2017,DD,RPS,DD,bat,normal,0,DD,7,0,Karun Nair,458.0,"Feroz Shah Kotla Stadium, Delhi",2,KN Ananthapadmanabhan,CK Nandan
628,2017_52,2017,Kanpur,13-05-2017,GL,SRH,SRH,field,normal,0,SRH,0,8,Mohammed Siraj,681.0,Green Park,34,AK Chaudhary,Nitin Menon
629,2017_53,2017,Kolkata,13-05-2017,MI,KKR,KKR,field,normal,0,MI,9,0,Ambati Rayudu,309.0,"Eden Garden Stadium, Kolkata, West Bengal",3,A Nand Kishore,S Ravi
630,2017_54,2017,Pune,14-05-2017,KXI,RPS,RPS,field,normal,0,RPS,0,9,Jaydev Unadkat,361.0,Maharashtra Cricket Association Stadium,32,AY Dandekar,A Deshmukh
631,2017_55,2017,Delhi,14-05-2017,RCB,DD,RCB,bat,normal,0,RCB,10,0,Harshal Patel,456.0,"Feroz Shah Kotla Stadium, Delhi",2,CK Nandan,C Shamshuddin
632,2017_56,2017,Mumbai,16-05-2017,RPS,MI,MI,field,normal,0,RPS,20,0,Washington Sunder,631.0,"Wankhede Stadium, Mumbai, Maharashtra",1,S Ravi,C Shamshuddin
633,2017_57,2017,Bangalore,17-05-2017,SRH,KKR,KKR,field,normal,1,KKR,0,7,Nathan Coulter-Nile,484.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,AK Chaudhary,Nitin Menon
634,2017_58,2017,Bangalore,19-05-2017,KKR,MI,MI,field,normal,0,MI,0,6,Karn Sharma,254.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,NJ Llong,Nitin Menon
635,2017_59,2017,Hyderabad,21-05-2017,MI,RPS,MI,bat,normal,0,MI,1,0,Krunal Pandya,582.0,"Rajiv Gandhi International Stadium, Hyderabad",4,NJ Llong,S Ravi

In [6]:
print(matches.shape)
print(matches.info())

(636, 19)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 19 columns):
match_id              636 non-null object
season                636 non-null int64
city                  629 non-null object
date                  636 non-null object
team1_id              636 non-null object
team2_id              636 non-null object
toss_winner           636 non-null object
toss_decision         636 non-null object
result                636 non-null object
dl_applied            636 non-null int64
winner                633 non-null object
win_by_runs           636 non-null int64
win_by_wickets        636 non-null int64
player_of_match       633 non-null object
player_of_match_id    633 non-null float64
venue                 636 non-null object
venue_id              636 non-null int64
umpire1               635 non-null object
umpire2               635 non-null object
dtypes: float64(1), int64(5), object(13)
memory usage: 94.5+ KB
None

In [7]:
print(matches.head(2))

  match_id  season        city        date team1_id team2_id toss_winner  \
0   2008_1    2008   Bangalore  18-04-2008      KKR      RCB         RCB
1   2008_2    2008  Chandigarh  19-04-2008      CSK      KXI         CSK

  toss_decision  result  dl_applied winner  win_by_runs  win_by_wickets  \
0         field  normal           0    KKR          140               0
1           bat  normal           0    CSK           33               0

    player_of_match  player_of_match_id  \
0  Brendon McCullum                82.0
1    Michael Hussey                18.0

                                               venue  venue_id    umpire1  \
0         M.Chinnaswamy Stadium Bengaluru, Karnataka         7  Asad Rauf
1  I.S. Bindra Punjab Cricket Association Stadium...         9  MR Benson

       umpire2
0  RE Koertzen
1   SL Shastri

In [8]:
print(matches.describe(include='all'))

       match_id       season    city        date team1_id team2_id  \
count       636   636.000000     629         636      636      636
unique      636          NaN      30         450       13       13
top     2013_63          NaN  Mumbai  21-03-2010       MI       DD
freq          1          NaN      85           2       82       84
mean        NaN  2012.490566     NaN         NaN      NaN      NaN
std         NaN     2.773026     NaN         NaN      NaN      NaN
min         NaN  2008.000000     NaN         NaN      NaN      NaN
25%         NaN  2010.000000     NaN         NaN      NaN      NaN
50%         NaN  2012.000000     NaN         NaN      NaN      NaN
75%         NaN  2015.000000     NaN         NaN      NaN      NaN
max         NaN  2017.000000     NaN         NaN      NaN      NaN

       toss_winner toss_decision  result  dl_applied winner  win_by_runs  \
count          636           636     636  636.000000    633   636.000000
unique          13             2       3         NaN     13          NaN
top             MI         field  normal         NaN     MI          NaN
freq            85           363     626         NaN     92          NaN
mean           NaN           NaN     NaN    0.025157    NaN    13.682390
std            NaN           NaN     NaN    0.156726    NaN    23.908877
min            NaN           NaN     NaN    0.000000    NaN     0.000000
25%            NaN           NaN     NaN    0.000000    NaN     0.000000
50%            NaN           NaN     NaN    0.000000    NaN     0.000000
75%            NaN           NaN     NaN    0.000000    NaN    20.000000
max            NaN           NaN     NaN    1.000000    NaN   146.000000

        win_by_wickets player_of_match  player_of_match_id  \
count       636.000000             633          633.000000
unique             NaN             201                 NaN
top                NaN     Chris Gayle                 NaN
freq               NaN              18                 NaN
mean          3.372642             NaN          209.751975
std           3.420338             NaN          180.132037
min           0.000000             NaN            1.000000
25%           0.000000             NaN           69.000000
50%           4.000000             NaN          149.000000
75%           7.000000             NaN          321.000000
max          10.000000             NaN          691.000000

                                             venue    venue_id  \
count                                          636  636.000000
unique                                          34         NaN
top     M.Chinnaswamy Stadium Bengaluru, Karnataka         NaN
freq                                            66         NaN
mean                                           NaN   10.179245
std                                            NaN    9.403096
min                                            NaN    1.000000
25%                                            NaN    3.000000
50%                                            NaN    7.000000
75%                                            NaN   14.000000
max                                            NaN   34.000000

                umpire1     umpire2
count               635         635
unique               44          45
top     HDPK Dharmasena  SJA Taufel
freq                 73          54
mean                NaN         NaN
std                 NaN         NaN
min                 NaN         NaN
25%                 NaN         NaN
50%                 NaN         NaN
75%                 NaN         NaN
max                 NaN         NaN

In [9]:
matches.iloc[1:4, [1,4,5]]
matches.head(2)

,match_id,season,city,date,team1_id,team2_id,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,player_of_match_id,venue,venue_id,umpire1,umpire2
0,2008_1,2008,Bangalore,18-04-2008,KKR,RCB,RCB,field,normal,0,KKR,140,0,Brendon McCullum,82.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,Asad Rauf,RE Koertzen
1,2008_2,2008,Chandigarh,19-04-2008,CSK,KXI,CSK,bat,normal,0,CSK,33,0,Michael Hussey,18.0,I.S. Bindra Punjab Cricket Association Stadium...,9,MR Benson,SL Shastri

In [10]:
matches.loc[1:4, ['season','team1_id','team2_id']]

   season team1_id team2_id
1    2008      CSK      KXI
2    2008       RR       DD
3    2008       MI      RCB
4    2008       DC      KKR

In [11]:
matches.city

0       Bangalore
1      Chandigarh
2           Delhi
3          Mumbai
4         Kolkata
5          Jaipur
6       Hyderabad
7         Chennai
8       Hyderabad
9      Chandigarh
10      Bangalore
11        Chennai
12         Mumbai
13     Chandigarh
14      Bangalore
15        Kolkata
16          Delhi
17      Hyderabad
18         Jaipur
19        Chennai
20      Hyderabad
21     Chandigarh
22         Mumbai
23         Jaipur
24      Bangalore
25        Chennai
26         Mumbai
27          Delhi
28        Kolkata
29         Jaipur
          ...
606     Bangalore
607       Kolkata
608    Chandigarh
609          Pune
610        Rajkot
611    Chandigarh
612     Hyderabad
613        Mumbai
614          Pune
615         Delhi
616       Kolkata
617         Delhi
618     Bangalore
619     Hyderabad
620         Delhi
621     Bangalore
622    Chandigarh
623     Hyderabad
624    Chandigarh
625        Kanpur
626        Mumbai
627         Delhi
628        Kanpur
629       Kolkata
630          Pune
631         Delhi
632        Mumbai
633     Bangalore
634     Bangalore
635     Hyderabad
Name: city, Length: 636, dtype: object

In [12]:
print(type(matches),type(matches.city))

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>

In [13]:
matches[['result','dl_applied']]

     result  dl_applied
0    normal           0
1    normal           0
2    normal           0
3    normal           0
4    normal           0
5    normal           0
6    normal           0
7    normal           0
8    normal           0
9    normal           0
10   normal           0
11   normal           0
12   normal           0
13   normal           0
14   normal           0
15   normal           0
16   normal           0
17   normal           0
18   normal           0
19   normal           0
20   normal           0
21   normal           0
22   normal           0
23   normal           0
24   normal           0
25   normal           0
26   normal           0
27   normal           0
28   normal           0
29   normal           0
..      ...         ...
606  normal           0
607  normal           0
608  normal           0
609  normal           0
610     tie           0
611  normal           0
612  normal           0
613  normal           0
614  normal           0
615  normal           0
616  normal           0
617  normal           0
618  normal           0
619  normal           0
620  normal           0
621  normal           0
622  normal           0
623  normal           0
624  normal           0
625  normal           0
626  normal           0
627  normal           0
628  normal           0
629  normal           0
630  normal           0
631  normal           0
632  normal           0
633  normal           1
634  normal           0
635  normal           0

[636 rows x 2 columns]

In [14]:
(matches.city == 'Delhi') | (matches.team1_id == 'DDV')

0      False
1      False
2       True
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16      True
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27      True
28     False
29     False
       ...
606    False
607    False
608    False
609    False
610    False
611    False
612    False
613    False
614    False
615     True
616    False
617     True
618    False
619    False
620     True
621    False
622    False
623    False
624    False
625    False
626    False
627     True
628    False
629    False
630    False
631     True
632    False
633    False
634    False
635    False
Length: 636, dtype: bool

In [ ]:
###  records of all the matched played by Delhi Daredevils or all the matches that are played in delhi

In [15]:
matches[(matches.city=='Delhi') | (matches.team1_id == 'DD') | (matches.team2_id == 'DD')]

,match_id,season,city,date,team1_id,team2_id,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,player_of_match_id,venue,venue_id,umpire1,umpire2
2,2008_3,2008,Delhi,19-04-2008,RR,DD,RR,bat,normal,0,DD,0,9,Farveez Maharoof,60.0,"Feroz Shah Kotla Stadium, Delhi",2,Aleem Dar,GA Pratapkumar
6,2008_7,2008,Hyderabad,22-04-2008,DC,DD,DC,bat,normal,0,DD,0,9,Virender Sehwag,46.0,"Rajiv Gandhi International Stadium, Hyderabad",4,IL Howell,AM Saheba
13,2008_14,2008,Chandigarh,27-04-2008,DD,KXI,DD,bat,normal,0,KXI,0,4,Simon Katich,105.0,I.S. Bindra Punjab Cricket Association Stadium...,9,RE Koertzen,I Shivram
16,2008_17,2008,Delhi,30-04-2008,DD,RCB,RCB,field,normal,0,DD,10,0,Glenn McGrath,50.0,"Feroz Shah Kotla Stadium, Delhi",2,Aleem Dar,I Shivram
19,2008_20,2008,Chennai,02-05-2008,CSK,DD,CSK,bat,normal,0,DD,0,8,Virender Sehwag,46.0,"M.A.Chidambaram Stadium Chennai, Tamil Nadu",5,BF Bowden,K Hariharan
22,2008_23,2008,Mumbai,04-05-2008,MI,DD,DD,field,normal,0,MI,29,0,Shaun Pollock,121.0,Dr DY Patil Sports Academy,10,IL Howell,RE Koertzen
27,2008_28,2008,Delhi,08-05-2008,DD,CSK,CSK,field,normal,0,CSK,0,4,Mahendra Singh Dhoni,1.0,"Feroz Shah Kotla Stadium, Delhi",2,Aleem Dar,RB Tiffin
33,2008_34,2008,Jaipur,11-05-2008,DD,RR,RR,field,normal,0,RR,0,3,Shane Watson,175.0,"Sawai Man Singh Stadium, Jaipur, Rajasthan",6,SJ Davis,RE Koertzen
35,2008_36,2008,Kolkata,13-05-2008,KKR,DD,KKR,bat,normal,0,KKR,23,0,Shoaib Akhtar,75.0,"Eden Garden Stadium, Kolkata, West Bengal",3,Asad Rauf,IL Howell
38,2008_39,2008,Delhi,15-05-2008,DD,DC,DC,field,normal,0,DD,12,0,Amit Mishra,52.0,"Feroz Shah Kotla Stadium, Delhi",2,BG Jerling,GA Pratapkumar
40,2008_41,2008,Delhi,17-05-2008,DD,KXI,DD,bat,normal,1,KXI,6,0,Mahela Jayawardene,101.0,"Feroz Shah Kotla Stadium, Delhi",2,AV Jayaprakash,RE Koertzen
44,2008_45,2008,Bangalore,19-05-2008,RCB,DD,DD,field,normal,0,DD,0,5,Shreevats Goswami,157.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,SJ Davis,GA Pratapkumar
49,2008_50,2008,Delhi,24-05-2008,MI,DD,DD,field,normal,0,DD,0,5,Dinesh Karthik,59.0,"Feroz Shah Kotla Stadium, Delhi",2,BF Bowden,K Hariharan
55,2008_56,2008,Mumbai,30-05-2008,RR,DD,DD,field,normal,0,RR,105,0,Shane Watson,175.0,"Wankhede Stadium, Mumbai, Maharashtra",1,BF Bowden,RE Koertzen
60,2009_3,2009,Cape Town,19-04-2009,KXI,DD,DD,field,normal,1,DD,0,10,Daniel Vettori,210.0,Newlands,11,MR Benson,SD Ranade
65,2009_8,2009,Durban,23-04-2009,DD,CSK,DD,bat,normal,0,DD,9,0,AB De Villiers,47.0,Kingsmead,13,BR Doctrove,SJA Taufel
69,2009_12,2009,Port Elizabeth,26-04-2009,RCB,DD,RCB,bat,normal,0,DD,0,6,Tillakaratne Dilshan,48.0,St George's Park,12,S Asnani,BG Jerling
73,2009_16,2009,Centurion,28-04-2009,DD,RR,DD,bat,normal,0,RR,0,5,Yusuf Pathan,171.0,SuperSport Park,14,GAV Baxter,RE Koertzen
76,2009_19,2009,Centurion,30-04-2009,DC,DD,DD,field,normal,0,DD,0,6,Dirk Nannes,204.0,SuperSport Park,14,GAV Baxter,AM Saheba
81,2009_24,2009,Johannesburg,02-05-2009,CSK,DD,DD,field,normal,0,CSK,18,0,Shadab Jakati,7.0,New Wanderers Stadium,16,DJ Harper,RE Koertzen
86,2009_29,2009,Durban,05-05-2009,KKR,DD,KKR,bat,normal,0,DD,0,9,Gautam Gambhir,58.0,Kingsmead,13,GAV Baxter,IL Howell
90,2009_33,2009,East London,08-05-2009,MI,DD,MI,bat,normal,0,DD,0,7,Ashish Nehra,119.0,Buffalo Park,15,M Erasmus,SK Tarapore
94,2009_37,2009,Johannesburg,10-05-2009,KKR,DD,DD,field,normal,0,DD,0,7,Amit Mishra,52.0,New Wanderers Stadium,16,SL Shastri,RB Tiffin
98,2009_41,2009,Durban,13-05-2009,DD,DC,DC,field,normal,0,DD,12,0,Rajat Bhatia,56.0,Kingsmead,13,DJ Harper,SL Shastri
101,2009_44,2009,Bloemfontein,15-05-2009,DD,KXI,KXI,field,normal,0,KXI,0,6,Brett Lee,94.0,OUTsurance Oval,18,HDPK Dharmasena,IL Howell
105,2009_48,2009,Bloemfontein,17-05-2009,DD,RR,DD,bat,normal,0,DD,14,0,AB De Villiers,47.0,OUTsurance Oval,18,SS Hazare,IL Howell
107,2009_50,2009,Johannesburg,19-05-2009,DD,RCB,DD,bat,normal,0,RCB,0,7,Jacques Kallis,148.0,New Wanderers Stadium,16,IL Howell,RB Tiffin
110,2009_53,2009,Centurion,21-05-2009,MI,DD,DD,field,normal,0,DD,0,4,Virender Sehwag,46.0,SuperSport Park,14,IL Howell,S Ravi
112,2009_55,2009,Centurion,22-05-2009,DD,DC,DC,field,normal,0,DC,0,6,Adam Gilchrist,28.0,SuperSport Park,14,BR Doctrove,DJ Harper
117,2010_3,2010,Chandigarh,13-03-2010,KXI,DD,DD,field,normal,0,DD,0,5,Gautam Gambhir,58.0,I.S. Bindra Punjab Cricket Association Stadium...,9,BR Doctrove,S Ravi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518,2016_2,2016,Kolkata,10-04-2016,DD,KKR,KKR,field,normal,0,KKR,0,9,Andre Russell,430.0,"Eden Garden Stadium, Kolkata, West Bengal",3,S Ravi,C Shamshuddin
523,2016_7,2016,Delhi,15-04-2016,KXI,DD,DD,field,normal,0,DD,0,8,Amit Mishra,52.0,"Feroz Shah Kotla Stadium, Delhi",2,S Ravi,C Shamshuddin
527,2016_11,2016,Bangalore,17-04-2016,RCB,DD,DD,field,normal,0,DD,0,7,Quinton de Kock,502.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,VA Kulkarni,A Nand Kishore
533,2016_17,2016,Delhi,23-04-2016,DD,MI,MI,field,normal,0,DD,10,0,Sanju Samson,439.0,"Feroz Shah Kotla Stadium, Delhi",2,S Ravi,C Shamshuddin
539,2016_23,2016,Delhi,27-04-2016,GL,DD,DD,field,normal,0,GL,1,0,Chris Morris,465.0,"Feroz Shah Kotla Stadium, Delhi",2,M Erasmus,S Ravi
542,2016_26,2016,Delhi,30-04-2016,DD,KKR,KKR,field,normal,0,DD,27,0,Carlos Brathwaite,567.0,"Feroz Shah Kotla Stadium, Delhi",2,KN Ananthapadmanabhan,M Erasmus
547,2016_31,2016,Rajkot,03-05-2016,GL,DD,DD,field,normal,0,DD,0,8,Rishabh Pant,572.0,Saurashtra Cricket Association Stadium,33,CB Gaffaney,BNJ Oxenford
549,2016_33,2016,Delhi,05-05-2016,DD,RPS,RPS,field,normal,0,RPS,0,7,Ajinkya Rahane,122.0,"Feroz Shah Kotla Stadium, Delhi",2,C Shamshuddin,RJ Tucker
552,2016_36,2016,Chandigarh,07-05-2016,KXI,DD,DD,field,normal,0,KXI,9,0,Marcus Stoinis,540.0,I.S. Bindra Punjab Cricket Association Stadium...,9,HDPK Dharmasena,CK Nandan
558,2016_42,2016,Hyderabad,12-05-2016,SRH,DD,DD,field,normal,0,DD,0,7,Chris Morris,465.0,"Rajiv Gandhi International Stadium, Hyderabad",4,K Bharatan,M Erasmus
563,2016_47,2016,Visakhapatnam,15-05-2016,MI,DD,DD,field,normal,0,MI,80,0,Krunal Pandya,582.0,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,25,Nitin Menon,CK Nandan
565,2016_49,2016,Visakhapatnam,17-05-2016,DD,RPS,RPS,field,normal,1,RPS,19,0,Ashok Dinda,68.0,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,25,Nitin Menon,C Shamshuddin
568,2016_52,2016,Raipur,20-05-2016,SRH,DD,DD,field,normal,0,DD,0,6,Karun Nair,458.0,Shaheed Veer Narayan Singh International Stadium,27,A Nand Kishore,BNJ Oxenford
572,2016_56,2016,Raipur,22-05-2016,DD,RCB,RCB,field,normal,0,RCB,0,6,Virat Kohli,149.0,Shaheed Veer Narayan Singh International Stadium,27,A Nand Kishore,BNJ Oxenford
574,2016_58,2016,Delhi,25-05-2016,SRH,KKR,KKR,field,normal,0,SRH,22,0,Moises Henriques,212.0,"Feroz Shah Kotla Stadium, Delhi",2,M Erasmus,C Shamshuddin
575,2016_59,2016,Delhi,27-05-2016,GL,SRH,SRH,field,normal,0,SRH,0,4,David Warner,207.0,"Feroz Shah Kotla Stadium, Delhi",2,M Erasmus,CK Nandan
581,2017_5,2017,Bangalore,08-04-2017,RCB,DD,RCB,bat,normal,0,RCB,15,0,Kedar Jadhav,249.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,NaN,NaN
585,2017_9,2017,Pune,11-04-2017,DD,RPS,RPS,field,normal,0,DD,97,0,Sanju Samson,439.0,Maharashtra Cricket Association Stadium,32,AY Dandekar,S Ravi
591,2017_15,2017,Delhi,15-04-2017,DD,KXI,DD,bat,normal,0,DD,51,0,Corey Anderson,519.0,"Feroz Shah Kotla Stadium, Delhi",2,YC Barde,Nitin Menon
594,2017_18,2017,Delhi,17-04-2017,DD,KKR,DD,bat,normal,0,KKR,0,4,Nathan Coulter-Nile,484.0,"Feroz Shah Kotla Stadium, Delhi",2,Nitin Menon,CK Nandan
597,2017_21,2017,Hyderabad,19-04-2017,SRH,DD,SRH,bat,normal,0,SRH,15,0,Kane Williamson,564.0,"Rajiv Gandhi International Stadium, Hyderabad",4,CB Gaffaney,NJ Llong
600,2017_24,2017,Mumbai,22-04-2017,MI,DD,DD,field,normal,0,MI,14,0,Mitchell McClenaghan,549.0,"Wankhede Stadium, Mumbai, Maharashtra",1,A Nand Kishore,S Ravi
607,2017_31,2017,Kolkata,28-04-2017,DD,KKR,KKR,field,normal,0,KKR,0,7,Gautam Gambhir,58.0,"Eden Garden Stadium, Kolkata, West Bengal",3,NJ Llong,S Ravi
611,2017_35,2017,Chandigarh,30-04-2017,DD,KXI,KXI,field,normal,0,KXI,0,10,Sandeep Sharma,479.0,I.S. Bindra Punjab Cricket Association Stadium...,9,YC Barde,CK Nandan
615,2017_39,2017,Delhi,02-05-2017,SRH,DD,DD,field,normal,0,DD,0,6,Mohammed Shami,647.0,"Feroz Shah Kotla Stadium, Delhi",2,YC Barde,Nitin Menon
617,2017_41,2017,Delhi,04-05-2017,GL,DD,DD,field,normal,0,DD,0,7,Rishabh Pant,572.0,"Feroz Shah Kotla Stadium, Delhi",2,M Erasmus,Nitin Menon
620,2017_44,2017,Delhi,06-05-2017,MI,DD,DD,field,normal,0,MI,146,0,Lendl Simmons,524.0,"Feroz Shah Kotla Stadium, Delhi",2,Nitin Menon,CK Nandan
625,2017_49,2017,Kanpur,10-05-2017,GL,DD,DD,field,normal,0,DD,0,2,Shreyas Iyer,537.0,Green Park,34,YC Barde,AK Chaudhary
627,2017_51,2017,Delhi,12-05-2017,DD,RPS,DD,bat,normal,0,DD,7,0,Karun Nair,458.0,"Feroz Shah Kotla Stadium, Delhi",2,KN Ananthapadmanabhan,CK Nandan
631,2017_55,2017,Delhi,14-05-2017,RCB,DD,RCB,bat,normal,0,RCB,10,0,Harshal Patel,456.0,"Feroz Shah Kotla Stadium, Delhi",2,CK Nandan,C Shamshuddin

In [16]:
matches.groupby(by='city').size().reset_index(name='counts')

              city  counts
0        Abu Dhabi       7
1        Ahmedabad      12
2        Bangalore      66
3     Bloemfontein       2
4        Cape Town       7
5        Centurion      12
6       Chandigarh      46
7          Chennai      48
8          Cuttack       7
9            Delhi      60
10      Dharamsala       9
11          Durban      15
12     East London       3
13       Hyderabad      49
14          Indore       5
15          Jaipur      33
16    Johannesburg       8
17          Kanpur       4
18       Kimberley       3
19           Kochi       5
20         Kolkata      61
21          Mumbai      85
22          Nagpur       3
23  Port Elizabeth       7
24            Pune      32
25          Raipur       6
26          Rajkot      10
27          Ranchi       7
28         Sharjah       6
29   Visakhapatnam      11

In [17]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 19 columns):
match_id              636 non-null object
season                636 non-null int64
city                  629 non-null object
date                  636 non-null object
team1_id              636 non-null object
team2_id              636 non-null object
toss_winner           636 non-null object
toss_decision         636 non-null object
result                636 non-null object
dl_applied            636 non-null int64
winner                633 non-null object
win_by_runs           636 non-null int64
win_by_wickets        636 non-null int64
player_of_match       633 non-null object
player_of_match_id    633 non-null float64
venue                 636 non-null object
venue_id              636 non-null int64
umpire1               635 non-null object
umpire2               635 non-null object
dtypes: float64(1), int64(5), object(13)
memory usage: 94.5+ KB

In [ ]:
### ### subset the records for each city and then count the number of records for each city

In [18]:
matches.groupby(by='city').agg(len)['match_id']

city
Abu Dhabi          7
Ahmedabad         12
Bangalore         66
Bloemfontein       2
Cape Town          7
Centurion         12
Chandigarh        46
Chennai           48
Cuttack            7
Delhi             60
Dharamsala         9
Durban            15
East London        3
Hyderabad         49
Indore             5
Jaipur            33
Johannesburg       8
Kanpur             4
Kimberley          3
Kochi              5
Kolkata           61
Mumbai            85
Nagpur             3
Port Elizabeth     7
Pune              32
Raipur             6
Rajkot            10
Ranchi             7
Sharjah            6
Visakhapatnam     11
Name: match_id, dtype: int64

In [19]:
matches.groupby(by="city").agg(sum)

,season,dl_applied,win_by_runs,win_by_wickets,player_of_match_id,venue_id
city,,,,,,
Abu Dhabi,14098,0,157,16,2102.0,203
Ahmedabad,24156,0,180,38,3354.0,240
Bangalore,132861,3,1263,232,12366.0,462
Bloemfontein,4018,0,14,6,141.0,36
Cape Town,14063,1,145,18,958.0,77
Centurion,24108,1,81,49,1215.0,168
Chandigarh,92582,0,576,167,11956.0,414
Chennai,96554,0,715,111,6166.0,240
Cuttack,14086,0,73,20,882.0,147
Delhi,120771,2,876,192,13204.0,120
Dharamsala,18103,0,279,23,1273.0,207
Durban,30135,1,159,33,1563.0,195
East London,6027,0,87,7,797.0,45
Hyderabad,98649,2,486,184,12024.0,196
Indore,10073,0,0,36,1623.0,40
Jaipur,66363,0,460,151,6726.0,198
Johannesburg,16072,0,25,35,743.0,128
Kanpur,8066,0,0,22,1366.0,136
Kimberley,6027,0,53,10,241.0,51
Kochi,10055,1,110,13,329.0,120
Kolkata,122783,3,587,224,10920.0,183
Mumbai,171049,0,1102,264,17863.0,436
Nagpur,6030,0,15,6,559.0,66
Port Elizabeth,14063,0,200,22,1138.0,84
Pune,64455,0,545,98,8373.0,922
Raipur,12088,0,21,25,1392.0,162
Rajkot,20165,0,70,48,4369.0,330
Ranchi,14097,0,41,24,995.0,196
Sharjah,12084,0,74,26,2196.0,180
Visakhapatnam,22165,2,282,22,3112.0,275

In [ ]:
### how many matches are played in a city, what is the average runs win or average wickets win, when is the most recent match played

In [20]:
matches.groupby(by='city').aggregate({
    'match_id':'count',
    'win_by_runs':'mean',
    'win_by_wickets':'mean',
    'date':['min','max']
})

               match_id win_by_runs win_by_wickets        date
                  count        mean           mean         min         max
city
Abu Dhabi             7   22.428571       2.285714  16-04-2014  29-04-2014
Ahmedabad            12   15.000000       3.166667  05-05-2014  28-03-2010
Bangalore            66   19.136364       3.515152  01-06-2014  29-05-2016
Bloemfontein          2    7.000000       3.000000  15-05-2009  17-05-2009
Cape Town             7   20.714286       2.571429  18-04-2009  26-04-2009
Centurion            12    6.750000       4.083333  06-05-2009  30-04-2009
Chandigarh           46   12.521739       3.630435  02-04-2010  30-04-2017
Chennai              48   14.895833       2.312500  01-05-2011  31-03-2010
Cuttack               7   10.428571       2.857143  01-05-2012  22-04-2012
Delhi                60   14.600000       3.200000  01-05-2015  31-03-2010
Dharamsala            9   31.000000       2.555556  15-05-2011  21-05-2011
Durban               15   10.600000       2.200000  01-05-2009  29-04-2009
East London           3   29.000000       2.333333  01-05-2009  08-05-2009
Hyderabad            49    9.918367       3.755102  01-05-2008  30-04-2017
Indore                5    0.000000       7.200000  08-04-2017  20-04-2017
Jaipur               33   13.939394       4.575758  01-05-2008  29-04-2013
Johannesburg          8    3.125000       4.375000  02-05-2009  24-05-2009
Kanpur                4    0.000000       5.500000  10-05-2017  21-05-2016
Kimberley             3   17.666667       3.333333  09-05-2009  11-05-2009
Kochi                 5   22.000000       2.600000  05-05-2011  30-04-2011
Kolkata              61    9.622951       3.672131  01-04-2010  30-04-2015
Mumbai               85   12.964706       3.105882  01-05-2015  31-05-2008
Nagpur                3    5.000000       2.000000  05-04-2010  12-04-2010
Port Elizabeth        7   28.571429       3.142857  02-05-2009  27-04-2009
Pune                 32   17.031250       3.062500  01-05-2016  30-04-2013
Raipur                6    3.500000       4.166667  01-05-2013  28-04-2013
Rajkot               10    7.000000       4.800000  01-05-2016  29-04-2017
Ranchi                7    5.857143       3.428571  02-05-2014  22-05-2015
Sharjah               6   12.333333       4.333333  17-04-2014  27-04-2014
Visakhapatnam        11   25.636364       2.000000  07-04-2012  22-04-2015

In [ ]:
### create a new variable which says if the match is won by chasing or not

In [21]:
matches['win_by_chase'] = matches.win_by_wickets>0
matches.sample(20)

,match_id,season,city,date,team1_id,team2_id,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,player_of_match_id,venue,venue_id,umpire1,umpire2,win_by_chase
96,2009_39,2009,Centurion,12-05-2009,KKR,RCB,RCB,field,normal,0,RCB,0,6,Ross Taylor,163.0,SuperSport Park,14,M Erasmus,SS Hazare,True
407,2014_10,2014,NaN,23-04-2014,CSK,RR,RR,field,normal,0,CSK,7,0,Ravindra Jadeja,177.0,Dubai International Cricket Stadium,31,HDPK Dharmasena,RK Illingworth,False
541,2016_25,2016,Pune,29-04-2016,RPS,GL,GL,field,normal,0,GL,0,3,Dwayne Smith,124.0,Maharashtra Cricket Association Stadium,32,CB Gaffaney,BNJ Oxenford,True
214,2011_40,2011,Delhi,02-05-2011,DD,KTK,KTK,field,normal,0,KTK,0,7,Prasanth Parameswaran,369.0,"Feroz Shah Kotla Stadium, Delhi",2,Asad Rauf,SL Shastri,True
239,2011_65,2011,Mumbai,20-05-2011,MI,RR,MI,bat,normal,0,RR,0,10,Shane Watson,175.0,"Wankhede Stadium, Mumbai, Maharashtra",1,RE Koertzen,PR Reiffel,True
207,2011_33,2011,Jaipur,29-04-2011,MI,RR,RR,field,normal,0,RR,0,7,Johan Botha,256.0,"Sawai Man Singh Stadium, Jaipur, Rajasthan",6,Asad Rauf,SK Tarapore,True
566,2016_50,2016,Bangalore,18-05-2016,RCB,KXI,KXI,field,normal,1,RCB,82,0,Virat Kohli,149.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,KN Ananthapadmanabhan,M Erasmus,False
184,2011_10,2011,Mumbai,13-04-2011,KTK,PW,KTK,bat,normal,0,PW,0,4,Mohnish Mishra,284.0,Dr DY Patil Sports Academy,10,S Asnani,PR Reiffel,True
49,2008_50,2008,Delhi,24-05-2008,MI,DD,DD,field,normal,0,DD,0,5,Dinesh Karthik,59.0,"Feroz Shah Kotla Stadium, Delhi",2,BF Bowden,K Hariharan,True
513,2015_56,2015,Mumbai,19-05-2015,MI,CSK,MI,bat,normal,0,MI,25,0,Kieron Pollard,315.0,"Wankhede Stadium, Mumbai, Maharashtra",1,HDPK Dharmasena,RK Illingworth,False
591,2017_15,2017,Delhi,15-04-2017,DD,KXI,DD,bat,normal,0,DD,51,0,Corey Anderson,519.0,"Feroz Shah Kotla Stadium, Delhi",2,YC Barde,Nitin Menon,False
99,2009_42,2009,Durban,14-05-2009,CSK,RCB,CSK,bat,normal,0,RCB,0,2,Ross Taylor,163.0,Kingsmead,13,BR Doctrove,DJ Harper,True
424,2014_27,2014,Mumbai,06-05-2014,MI,RCB,RCB,field,normal,0,MI,19,0,Rohit Sharma,30.0,"Wankhede Stadium, Mumbai, Maharashtra",1,S Ravi,K Srinath,False
131,2010_17,2010,Mumbai,22-03-2010,KKR,MI,KKR,bat,normal,0,MI,0,7,Sachin Tendulkar,113.0,Brabourne Stadium,19,SS Hazare,SJA Taufel,True
490,2015_33,2015,Bangalore,02-05-2015,KKR,RCB,RCB,field,normal,0,RCB,0,7,Mandeep Singh,373.0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,JD Cloete,PG Pathak,True
9,2008_10,2008,Chandigarh,25-04-2008,KXI,MI,MI,field,normal,0,KXI,66,0,Kumar Sangakkara,98.0,I.S. Bindra Punjab Cricket Association Stadium...,9,Aleem Dar,AM Saheba,False
455,2014_58,2014,Mumbai,28-05-2014,MI,CSK,CSK,field,normal,0,CSK,0,7,Suresh Raina,24.0,Brabourne Stadium,19,VA Kulkarni,BNJ Oxenford,True
211,2011_37,2011,Jaipur,01-05-2011,PW,RR,RR,field,normal,0,RR,0,6,Ross Taylor,163.0,"Sawai Man Singh Stadium, Jaipur, Rajasthan",6,SK Tarapore,SJA Taufel,True
133,2010_19,2010,Chandigarh,24-03-2010,RR,KXI,KXI,field,normal,0,RR,31,0,Adam Voges,324.0,I.S. Bindra Punjab Cricket Association Stadium...,9,BR Doctrove,SK Tarapore,False
559,2016_43,2016,Visakhapatnam,13-05-2016,MI,KXI,MI,bat,normal,0,KXI,0,7,Marcus Stoinis,540.0,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,25,HDPK Dharmasena,CK Nandan,True

In [ ]:
#### What is the win percentage of `Chennai Super Kings`?

In [22]:
cs = matches[(matches.team1_id == 'CSK') | (matches.team2_id == 'CSK' ) ]
cswins = sum(cs.winner == 'CSK')
cswinsp = 100 * cswins/cs.shape[0]
print('CSK has won {:.2f}% of matches '.format(100*cswins/cs.shape[0]))
print(cswinsp)

CSK has won 60.31% of matches
60.30534351145038

In [23]:
cs = matches[(matches.team1_id == 'CSK') | (matches.team2_id == 'CSK')]['winner']
wins = sum(cs == 'CSK')
print('CSK has won {:.2f}% of matches '.format(100*wins/cs.shape[0]))

CSK has won 60.31% of matches

In [ ]:
### What are all the ids of matches played in season 2012? How many matches were played in 2012?

In [24]:
ids_2012 = matches[matches.season == 2012]['match_id'].unique()
len(ids_2012)

74

In [25]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 20 columns):
match_id              636 non-null object
season                636 non-null int64
city                  629 non-null object
date                  636 non-null object
team1_id              636 non-null object
team2_id              636 non-null object
toss_winner           636 non-null object
toss_decision         636 non-null object
result                636 non-null object
dl_applied            636 non-null int64
winner                633 non-null object
win_by_runs           636 non-null int64
win_by_wickets        636 non-null int64
player_of_match       633 non-null object
player_of_match_id    633 non-null float64
venue                 636 non-null object
venue_id              636 non-null int64
umpire1               635 non-null object
umpire2               635 non-null object
win_by_chase          636 non-null bool
dtypes: bool(1), float64(1), int64(5), object(13)
memory usage: 95.1+ KB

In [26]:
deliveries = pd.read_csv("deliveries.csv")

In [27]:
deliveries.head(2)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [ ]:
### Which batsman scored the most runs?

In [28]:
batsmen = deliveries.groupby(by='batsman').aggregate(sum)['batsman_runs']
batsmen.sort_values(ascending=False).head(1)
batsmen

batsman
A Ashish Reddy           280
A Chandila                 4
A Chopra                  53
A Choudhary               25
A Flintoff                62
A Kumble                  35
A Mishra                 340
A Mithun                  34
A Mukund                  19
A Nehra                   41
A Singh                    2
A Symonds                974
A Uniyal                   4
A Zampa                    5
AA Bilakhia               69
AA Chavan                 12
AA Jhunjhunwala          217
AA Noffke                  9
AB Agarkar               179
AB Barath                 42
AB Dinda                  26
AB McDonald              123
AB de Villiers          3486
AC Blizzard              120
AC Gilchrist            2069
AC Thomas                 20
AC Voges                 181
AD Mascarenhas            79
AD Mathews               724
AD Nath                   20
                        ...
V Kohli                 4423
V Pratap Singh             0
V Sehwag                2728
V Shankar                101
VH Zol                    29
VR Aaron                  46
VRV Singh                  4
VS Malik                   7
VS Yeligati                2
VVS Laxman               282
VY Mahesh                 15
Vishnu Vinod              19
W Jaffer                 130
WA Mota                   56
WD Parnell                63
WP Saha                 1557
WPUJC Vaas                81
Washington Sundar          9
X Thalaivan Sargunam      10
Y Gnaneswara Rao          19
Y Nagar                  285
Y Venugopal Rao          985
YA Abdulla                 0
YK Pathan               2922
YS Chahal                 15
YV Takawale              192
Yashpal Singh             47
Younis Khan                3
Yuvraj Singh            2591
Z Khan                   117
Name: batsman_runs, Length: 461, dtype: int64

In [ ]:
### How many matches were played each season?

In [29]:
n_matches = matches.groupby(by='season').count()['match_id']
n_matches

season
2008    58
2009    57
2010    60
2011    73
2012    74
2013    76
2014    60
2015    59
2016    60
2017    59
Name: match_id, dtype: int64

In [30]:
deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
5,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,6,S Dhawan,DA Warner,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,7,S Dhawan,DA Warner,TS Mills,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
7,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,1,S Dhawan,DA Warner,A Choudhary,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
8,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,2,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
9,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,3,DA Warner,S Dhawan,A Choudhary,0,...,0,0,1,0,0,1,1,NaN,NaN,NaN
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
11,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,5,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,DA Warner,caught,Mandeep Singh
12,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,6,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,7,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
14,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,1,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
15,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,2,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
16,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,3,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
17,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,4,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
18,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,5,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
19,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,6,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
20,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,1,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
21,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,2,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
22,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,3,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
23,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,4,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
24,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,5,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
25,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,6,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
26,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,1,S Dhawan,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
27,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,2,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
28,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,3,S Dhawan,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
29,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,4,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150430,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,1,KL Rahul,SR Watson,BCJ Cutting,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150431,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,2,SR Watson,KL Rahul,BCJ Cutting,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150432,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,3,KL Rahul,SR Watson,BCJ Cutting,0,...,0,0,0,0,0,0,0,KL Rahul,bowled,NaN
150433,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,4,Sachin Baby,SR Watson,BCJ Cutting,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
150434,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,5,Sachin Baby,SR Watson,BCJ Cutting,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150435,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,6,SR Watson,Sachin Baby,BCJ Cutting,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150436,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,1,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
150437,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,2,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150438,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,3,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,0,0,0,SR Watson,caught,MC Henriques
150439,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,4,Sachin Baby,STR Binny,Mustafizur Rahman,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150440,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,5,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150441,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,6,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150442,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,1,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
150443,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,2,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150444,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,3,Sachin Baby,STR Binny,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150445,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,4,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
150446,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,5,STR Binny,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150447,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,6,Sachin Baby,STR Binny,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
150448,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,1,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,1,0,1,STR Binny,run out,DJ Hooda
150449,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,2,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150450,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,3,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
150451,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,4,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150452,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,5,Sachin Baby,CJ Jordan,Mustafizur Rahman,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150453,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,6,Sachin Baby,CJ Jordan,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150454,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,1,CJ Jordan,Sachin Baby,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [ ]:
### How many runs did Sehwag score against each team?

In [31]:
seh = deliveries[deliveries.batsman == 'V Sehwag'][['batsman_runs', 'bowling_team']]
seh_runs = seh.groupby(by='bowling_team').sum()
seh_runs

                             batsman_runs
bowling_team
Chennai Super Kings                   405
Deccan Chargers                       317
Delhi Daredevils                       80
Kings XI Punjab                       250
Kochi Tuskers Kerala                   95
Kolkata Knight Riders                 305
Mumbai Indians                        431
Pune Warriors                         220
Rajasthan Royals                      316
Royal Challengers Bangalore           255
Sunrisers Hyderabad                    54

In [33]:
#How many runs did Sehwag score in all?
print('V Sehwag', seh['batsman_runs'].sum())

V Sehwag 2728